# Generated by Django 6.0.1 on 2026-04-20 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price'),
        ('enrollments', '0002_enrollment_batch_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.PositiveIntegerField(help_text='Amount claimed by student, in paise')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer')], default='UPI', max_length=10)),
                ('utr_number', models.CharField(max_length=30)),
                ('payment_date', models.DateField()),
                ('receipt', models.ImageField(upload_to='enrollment_receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='enrollments_status_2e6242_idx'), models.Index(fields=['user', 'status'], name='enrollments_user_id_a78a79_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user', 'course'), name='unique_pending_request_per_user_course')],
            },
        ),
    ]
