# Generated by Django 6.0.1 on 2026-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_subscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='enrollments_user_id_18b905_idx',
            old_name='enrollments_sub_uc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='enrollments_expires_066158_idx',
            old_name='enrollments_sub_expires_idx',
        ),
    ]
