# Generated by Django 6.0.1 on 2026-05-29 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_chapter_covered_at_chapter_is_covered_and_more'),
        ('enrollments', '0005_rename_enrollments_sub_uc_status_idx_enrollments_user_id_18b905_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.batch'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['batch', 'status'], name='enrollments_batch_i_ca22c6_idx'),
        ),
    ]
