# Generated by Django 6.0.1 on 2026-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_subscription_trial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='enrollments_kind_f5124b_idx',
            old_name='enrollments_kind_status_exp_idx',
        ),
    ]
