# Generated by Django 6.0.1 on 2026-06-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_learnerprofile_and_more'),
        ('courses', '0013_chapter_covered_at_chapter_is_covered_and_more'),
        ('enrollments', '0008_rename_enrollments_kind_status_exp_idx_enrollments_kind_f5124b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentrequest',
            name='unique_pending_request_per_user_course',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_trial_per_user_course',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_user_id_ad8d71_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_batch_i_ca22c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollmentrequest',
            name='enrollments_user_id_a78a79_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='enrollments_user_id_18b905_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='enrollments_kind_f5124b_idx',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.learnerprofile'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='accounts.learnerprofile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.learnerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('learner_profile', 'course')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['learner_profile', 'course'], name='enrollments_learner_c5d010_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentrequest',
            index=models.Index(fields=['learner_profile', 'status'], name='enrollments_learner_36ed0b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['learner_profile', 'course', 'status'], name='enrollments_learner_aac19f_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('learner_profile', 'course'), name='unique_pending_request_per_learner_course'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_ended_email_sent_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_reminder_2d_sent_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_reminder_7d_sent_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='batch',
        ),
    ]
