# Generated by Django 6.0.1 on 2026-08-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_subjectteacher'),
        ('enrollments', '0010_enrollment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='courses.batch'),
        ),
    ]
