# Generated by Django 6.0.1 on 2026-07-17 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_class_level_course_kind_course_status_and_more'),
        ('livestream', '0003_livesessionchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='courses.batch'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['batch', 'start_time'], name='livestream__batch_i_4282a4_idx'),
        ),
    ]
