# Generated by Django 6.0.1 on 2026-07-19 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_livesession_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='actual_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='actual_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='peak_viewers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesessionattendance',
            name='total_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LiveKitWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='livestream.livesession')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type'], name='livestream__event_t_49b3dc_idx'), models.Index(fields=['room_name'], name='livestream__room_na_22d766_idx'), models.Index(fields=['received_at'], name='livestream__receive_e8e0c7_idx'), models.Index(fields=['processed'], name='livestream__process_4b2202_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionAttendanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_reconcile', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_intervals', to='livestream.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['session', 'user'], name='livestream__session_c107bd_idx'), models.Index(fields=['session', 'joined_at'], name='livestream__session_6912a2_idx'), models.Index(fields=['session', 'left_at'], name='livestream__session_2b6a8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionViewerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('viewers', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_samples', to='livestream.livesession')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['session', 'ts'], name='livestream__session_6b1170_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamHealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('fps', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('packet_loss', models.FloatField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('is_presenter', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_samples', to='livestream.livesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['session', 'ts'], name='livestream__session_f278aa_idx'), models.Index(fields=['session', 'is_presenter', 'ts'], name='livestream__session_5d133a_idx')],
            },
        ),
    ]
