# Generated by Django 6.0.1 on 2026-08-20 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_tourstate'),
        ('livestream', '0007_livesession_extended_until_livesession_series_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livesessionattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='livesessionattendance',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_attendances', to='accounts.learnerprofile'),
        ),
        migrations.AddField(
            model_name='livesessionattendanceinterval',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_attendance_intervals', to='accounts.learnerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='livesessionattendance',
            unique_together={('session', 'user', 'learner_profile')},
        ),
        migrations.AddIndex(
            model_name='livesessionattendance',
            index=models.Index(fields=['session', 'learner_profile'], name='livestream__session_c00fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='livesessionattendanceinterval',
            index=models.Index(fields=['session', 'learner_profile'], name='livestream__session_ef0852_idx'),
        ),
    ]
