# Generated by Django 6.0.1 on 2026-08-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_sessionrecording_uploaded_by"),
        ("livestream", "0010_livesession_chapter_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSessionEgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "egress_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("START_FAILED", "Start failed"),
                            ("EGRESS_STARTING", "Starting"),
                            ("EGRESS_ACTIVE", "Active"),
                            ("EGRESS_ENDING", "Ending"),
                            ("EGRESS_COMPLETE", "Complete"),
                            ("EGRESS_FAILED", "Failed"),
                            ("EGRESS_ABORTED", "Aborted"),
                            ("EGRESS_LIMIT_REACHED", "Limit reached"),
                        ],
                        default="REQUESTED",
                        max_length=32,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("error", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fetch_attempts", models.PositiveSmallIntegerField(default=0)),
                ("raw_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="egress_attempts",
                        to="courses.sessionrecording",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="egresses",
                        to="livestream.livesession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "live session egresses",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-requested_at"],
                        name="livestream__session_c15360_idx",
                    ),
                    models.Index(
                        fields=["status"], name="livestream__status_eb93d5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("egress_id", ""), _negated=True),
                        fields=("egress_id",),
                        name="uniq_livesessionegress_egress_id_when_set",
                    )
                ],
            },
        ),
    ]
