# Generated by Django 6.0.1 on 2026-08-07 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_settings_surface'),
        ('courses', '0026_boardnotifyrequest'),
        ('enrollments', '0010_enrollment_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text="0-indexed position in this student's paper.")),
                ('subject', models.CharField(max_length=30)),
                ('difficulty', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text='4 strings, in the shuffled order shown to this student.')),
                ('correct_option_index', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for the whole scholarship module.')),
                ('question_count', models.PositiveSmallIntegerField(default=50)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('difficulty_easy_pct', models.PositiveSmallIntegerField(default=60)),
                ('difficulty_medium_pct', models.PositiveSmallIntegerField(default=30)),
                ('difficulty_hard_pct', models.PositiveSmallIntegerField(default=10)),
                ('eligibility_policy', models.CharField(choices=[('per_year', 'One attempt per verified person per academic year')], default='per_year', max_length=20)),
                ('award_valid_until_month', models.PositiveSmallIntegerField(default=5)),
                ('award_valid_until_day', models.PositiveSmallIntegerField(default=31)),
                ('allow_digilocker', models.BooleanField(default=True)),
                ('allow_aadhaar_otp', models.BooleanField(default=True)),
                ('allow_manual_review', models.BooleanField(default=True)),
                ('active_kyc_provider', models.CharField(blank=True, help_text="Licensed reseller handling DigiLocker/Aadhaar OTP calls (e.g. setu, digio, surepass, hyperverge). ShikshaCom must never call UIDAI directly or store an Aadhaar number/hash — only the reseller's opaque, non-reversible verification reference.", max_length=30)),
                ('enable_device_fingerprint', models.BooleanField(default=True)),
                ('enable_tab_switch_tracking', models.BooleanField(default=True)),
                ('tab_switch_flag_threshold', models.PositiveSmallIntegerField(default=5, help_text='Tab-switches at/above this count auto-flags the session for admin review.')),
                ('answer_burst_seconds_threshold', models.PositiveSmallIntegerField(default=3, help_text='Answering faster than this, repeatedly, is logged as a suspicious burst.')),
                ('answer_burst_count_threshold', models.PositiveSmallIntegerField(default=10, help_text='Number of burst-fast answers in one session before it is auto-flagged.')),
                ('auto_review_top_bands', models.BooleanField(default=False)),
                ('top_band_review_min_pct', models.PositiveSmallIntegerField(default=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scholarship settings',
                'verbose_name_plural': 'Scholarship settings',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('change_count', models.PositiveSmallIntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='scholarship.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired (auto-submitted at deadline)'), ('voided', 'Voided by admin')], default='in_progress', max_length=15)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('awarded_discount_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subject_breakdown', models.JSONField(blank=True, default=dict)),
                ('tab_switch_count', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_status', models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('voided', 'Voided')], max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_exam_sessions', to='courses.course')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_exam_sessions', to='accounts.learnerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scholarship.examsession'),
        ),
        migrations.CreateModel(
            name='GuardianVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('digilocker', 'DigiLocker'), ('aadhaar_otp', 'Aadhaar OTP'), ('manual', 'Manual document review')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('provider', models.CharField(blank=True, help_text='Licensed KYC reseller used (setu/digio/surepass/...). Blank for manual.', max_length=30)),
                ('provider_reference', models.CharField(blank=True, help_text='Opaque, non-reversible verification token from the reseller. Never the Aadhaar number.', max_length=200)),
                ('verified_adult_name', models.CharField(blank=True, max_length=200)),
                ('verified_adult_dob', models.DateField(blank=True, null=True)),
                ('manual_document', models.FileField(blank=True, null=True, upload_to='scholarship/guardian_docs/%Y/%m/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_verifications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_pct', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('locked', 'Locked (earned during free launch)'), ('active', 'Active (real discount, redeemable)'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('voided', 'Voided by admin')], default='locked', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_awards', to='courses.course')),
                ('exam_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='award', to='scholarship.examsession')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_awards', to='accounts.learnerprofile')),
                ('redeemed_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='enrollments.enrollment')),
                ('redeemed_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='enrollments.subscription')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_correct', models.PositiveSmallIntegerField()),
                ('max_correct', models.PositiveSmallIntegerField()),
                ('discount_pct', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-min_correct'],
                'constraints': [models.UniqueConstraint(fields=('min_correct', 'max_correct'), name='scholarship_band_unique_range')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipEligibilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('reserved', 'Reserved (exam in progress)'), ('consumed', 'Consumed (exam submitted)'), ('voided', 'Voided by admin')], default='reserved', max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian_verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_records', to='scholarship.guardianverification')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_eligibility_records', to='accounts.learnerprofile')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examsession',
            name='eligibility_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exam_session', to='scholarship.scholarshipeligibilityrecord'),
        ),
        migrations.CreateModel(
            name='ScholarshipQuestionBankItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_level', models.PositiveSmallIntegerField(help_text='8-12, matches courses.Course.class_level')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('general_knowledge', 'General Knowledge'), ('current_affairs', 'Current Affairs')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Challenging')], max_length=10)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option_index', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are excluded from generation without deleting exam history that references them.')),
                ('source', models.CharField(choices=[('manual', 'Manually written'), ('ai_generated', 'AI-generated')], default='manual', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examquestion',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.scholarshipquestionbankitem'),
        ),
        migrations.CreateModel(
            name='CheatSignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_hidden', 'Tab hidden'), ('focus_lost', 'Window focus lost'), ('paste_detected', 'Paste detected'), ('devtools_suspected', 'DevTools suspected'), ('answer_burst', 'Answer burst (suspiciously fast)'), ('ip_changed', 'IP address changed mid-session'), ('multi_device', 'Multiple devices detected')], max_length=25)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_signals', to='scholarship.examsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='scholarship_session_73297e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='guardianverification',
            index=models.Index(fields=['account', 'status'], name='scholarship_account_90dbab_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipaward',
            index=models.Index(fields=['learner_profile', 'status'], name='scholarship_learner_b79440_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipaward',
            index=models.Index(fields=['status', 'expires_at'], name='scholarship_status_f81f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipeligibilityrecord',
            index=models.Index(fields=['learner_profile', 'academic_year'], name='scholarship_learner_6a462c_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipeligibilityrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'consumed'])), fields=('dedup_hash', 'academic_year'), name='scholarship_one_active_attempt_per_year'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'deadline'], name='scholarship_status_e66245_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['learner_profile'], name='scholarship_learner_5b16e1_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['flagged_for_review'], name='scholarship_flagged_1a1237_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipquestionbankitem',
            index=models.Index(fields=['class_level', 'subject', 'difficulty', 'is_active'], name='scholarship_class_l_6c8bee_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='scholarship_examquestion_unique_order'),
        ),
    ]
