# Generated by Django 6.0.1 on 2026-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipsettings',
            name='allow_aadhaar_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guardianverification',
            name='method',
            field=models.CharField(choices=[('digilocker', 'DigiLocker'), ('aadhaar_otp', 'Aadhaar OTP'), ('aadhaar_offline', 'Aadhaar (Offline e-KYC)'), ('manual', 'Manual document review')], max_length=15),
        ),
        migrations.AlterField(
            model_name='scholarshipsettings',
            name='allow_aadhaar_otp',
            field=models.BooleanField(default=False),
        ),
    ]
