# Generated by Django 6.0.1 on 2026-04-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_privatesession_active_connections_privatesession_all_left_at'),
    ]

    # NOTE: 0001_initial.py was regenerated at some point after these renames
    # had already happened on the live database, so it now creates every
    # index directly under its FINAL name (sessions_ap_teacher_73c4a5_idx,
    # sessions_ap_session_f6dc4b_idx, etc. — see 0001_initial's AddIndex
    # calls). That means a fresh migration replay never has the OLD names
    # this migration tries to rename from, and RenameIndex fails with
    # "No index named sessions_ap_chat_idx on model ChatMessage".
    #
    # On any database where this migration already ran for real, the
    # rename already happened — emptying the operations here changes
    # nothing there (Django never re-runs an applied migration). This only
    # fixes replay onto a fresh database, where the target names already
    # exist from 0001_initial and there is nothing left to rename.
    operations = [
    ]
