# Generated by Django 6.0.1 on 2026-05-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0008_group_session_instant_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupsession',
            new_name='sessions_ap_host_id_79fd19_idx',
            old_name='sessions_ap_host_sg_idx',
        ),
        migrations.RenameIndex(
            model_name='groupsession',
            new_name='sessions_ap_status_941250_idx',
            old_name='sessions_ap_sg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupsession',
            new_name='sessions_ap_schedul_660d80_idx',
            old_name='sessions_ap_sg_date_idx',
        ),
        migrations.RenameIndex(
            model_name='groupsessionchatmessage',
            new_name='sessions_ap_session_525a5c_idx',
            old_name='sessions_ap_session_chatidx',
        ),
        migrations.RenameIndex(
            model_name='groupsessioninvite',
            new_name='sessions_ap_user_id_be5a37_idx',
            old_name='sessions_ap_inv_user_idx',
        ),
        migrations.RenameIndex(
            model_name='groupsessioninvite',
            new_name='sessions_ap_session_cefc2f_idx',
            old_name='sessions_ap_inv_sess_idx',
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='invited_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsessionchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsessioninvite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
