# Generated by Django 6.0.1 on 2026-07-18 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_seed_documents_rbac'),
        ('sessions_app', '0009_rename_sessions_ap_host_sg_idx_sessions_ap_host_id_79fd19_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatesession',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_sessions', to='accounts.learnerprofile'),
        ),
        migrations.AddIndex(
            model_name='privatesession',
            index=models.Index(fields=['learner_profile', 'status'], name='sessions_ap_learner_578874_idx'),
        ),
    ]
