# Generated by Django 6.0.1 on 2026-07-25 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _blank_room_names_to_null(apps, schema_editor):
    """Pre-live sessions still carry the old blank-string default ("").
    Multiple rows share that value, which would violate the unique
    constraint we're about to add — collapse them to NULL first (NULLs
    don't collide under a unique constraint)."""
    GroupSession = apps.get_model('sessions_app', 'GroupSession')
    GroupSession.objects.filter(room_name='').update(room_name=None)


def _null_room_names_to_blank(apps, schema_editor):
    GroupSession = apps.get_model('sessions_app', 'GroupSession')
    GroupSession.objects.filter(room_name__isnull=True).update(room_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0010_privatesession_learner_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Nullable first (no unique yet) so the data migration below can
        # actually write NULL — then backfill, then add the constraint.
        # Doing it in one AlterField would try to write NULLs into a
        # still-NOT-NULL column.
        migrations.AlterField(
            model_name='groupsession',
            name='room_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RunPython(_blank_room_names_to_null, _null_room_names_to_blank),
        migrations.AlterField(
            model_name='groupsession',
            name='room_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GroupSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sessions_app.groupsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'user'], name='sessions_ap_session_ac2568_idx'), models.Index(fields=['session', 'joined_at'], name='sessions_ap_session_8ab15f_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupSessionAttendanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_reconcile', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_intervals', to='sessions_app.groupsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['session', 'user'], name='sessions_ap_session_1bdd4f_idx'), models.Index(fields=['session', 'joined_at'], name='sessions_ap_session_1eef6c_idx'), models.Index(fields=['session', 'left_at'], name='sessions_ap_session_5df43c_idx')],
            },
        ),
    ]
