# Generated by Django 6.0.1 on 2026-08-16 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0014_privatesessionattendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='cap_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='extensions_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RemoteControlGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='requested', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, max_length=16)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_controlling', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_grants', to='sessions_app.groupsession')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='session_files/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('saved_to_course', models.BooleanField(default=False, help_text='Survives the purge — copied into course materials.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sessions_app.groupsession')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_sharing_screen', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sessions_app.groupsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'left_at'], name='sessions_ap_session_bdb6d0_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
