# PLACEMENT: backend/content/management/commands/_homepage_seed_data.py
#
# The homepage copy that has always been HARDCODED in the React components,
# transcribed verbatim so seed_homepage_defaults can materialise it as CMS
# rows. Mirrors the convention of courses/.../_catalog_seed_data.py.
#
# TRANSCRIBED, NOT AUTHORED. Every string here is copied from the frontend
# fallback constants listed in the per-group comments below. Seeding these
# must leave the rendered page byte-identical -- the only change is that the
# copy now comes from the database and is editable in Admin-dashboard.
#
# Source of truth for each group (shiksha-frontend/src/components/):
#   home/Hero.jsx:213                 hero block + 3 floaters
#   home/WhyShiksha.jsx:64            why_shiksha block + 6 cards
#   home/TeachersStudents.jsx:58      teachers_students block + 2 cards
#   home/BrowseCategories.jsx:80      browse_categories block + 3 cards
#   home/WhyChooseShiksha.jsx:87,97   why_choose block + 3 cards + 3 badges
#   home/Resources.jsx:111            resources block + 6 cards
#   home/Collaborate.jsx:115,129,135  collaborate block + marquee/stat chips
#   home/Cta.jsx:25                   cta block
#   courses/CoursesHero.jsx:139       courses_hero block
#   home/Faq.jsx:29                   6 home FAQs
#   Faq.jsx:4                         4 legacy /faq page FAQs (page="general")
#   home/homeData.js:19               18 showcase cards
#
# Known deliberate omissions (no column exists for them; they stay in code):
#   * Hero's inline HERO_ART_SVG fallback illustration (Hero.jsx:209)
#   * TeachersStudents' positional pill labels / illustrations (DUO_META:38)
#   * The 7 competitive cards' per-tutor avatar tint (homeData.js `avColor`)
#   * The "all" filter tab is a RESERVED SENTINEL and is never a stored
#     category -- 3 source cards carried it and it was dropped from each.

# HomeContentBlock -- one singleton row per homepage section.
BLOCKS = [   # FEATURED_COURSES and FAQ render their *items* from ShowcaseCourse /
    # FAQItem, but their section heading was hardcoded in the component until
    # now (FeaturedCourses.jsx:557-559, home/Faq.jsx:121-122). These two blocks
    # exist so that heading is editable too. The `em`-highlighted second half of
    # each <h2> maps to heading_secondary, same as Hero.
    {   'section': 'featured_courses',
        'eyebrow': 'Featured Courses',
        'heading': 'Explore our',
        'heading_secondary': 'popular courses',
        'subhead': 'Some of our most popular academic and competitive programs, '
                   'built to help learners succeed with structured guidance.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'faq',
        'eyebrow': 'Frequently Asked Questions',
        'heading': 'Have questions?',
        'heading_secondary': "We've got answers.",
        'subhead': '',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'hero',
        'eyebrow': 'Empowerment Through Education',
        'heading': 'Empowering Students Through',
        'heading_secondary': 'Better Learning.',
        'subhead': 'ShikshaCom combines quality education, expert mentorship, '
                   'collaborative learning, and trusted resources to help every '
                   'student reach their academic goals.',
        'body': '',
        'cta_primary_label': 'Explore Courses',
        'cta_primary_href': '/courses',
        'cta_secondary_label': 'Book a Tutor',
        'cta_secondary_href': '/skill/browse',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'why_shiksha',
        'eyebrow': '',
        'heading': 'Why learners choose Shiksha',
        'heading_secondary': '',
        'subhead': 'Everything a student needs to learn, practise and grow — in one '
                   'place.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'teachers_students',
        'eyebrow': 'Teachers & Students',
        'heading': 'What are you looking for?',
        'heading_secondary': '',
        'subhead': '',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'browse_categories',
        'eyebrow': 'Browse Categories',
        'heading': 'Explore our learning categories',
        'heading_secondary': '',
        'subhead': 'Choose the path that matches your academic goals — programs '
                   'designed by experienced educators.',
        'body': '',
        'cta_primary_label': 'All categories',
        'cta_primary_href': '/courses',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'why_choose',
        'eyebrow': 'Why ShikshaCom',
        'heading': 'Why choose ShikshaCom?',
        'heading_secondary': '',
        'subhead': '',
        'body': 'ShikshaCom brings structured learning, expert mentorship and flexible '
                'digital education together — an engaging way to learn for school and '
                'everything after it.',
        'cta_primary_label': 'More details',
        'cta_primary_href': '/why-shiksha',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'resources',
        'eyebrow': 'Resources & Support',
        'heading': 'Beyond the classroom',
        'heading_secondary': '',
        'subhead': 'Extra resources, guidance and opportunities to support students '
                   'throughout their academic journey.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'collaborate',
        'eyebrow': 'Live Collaboration',
        'heading': 'Learn together, anywhere',
        'heading_secondary': '',
        'subhead': 'Host or join secure live sessions for classes, meetings, '
                   'workshops, mentoring, interviews, study groups, and collaborative '
                   'discussions — all from one platform.',
        'body': '',
        'cta_primary_label': 'Join Session',
        'cta_primary_href': '/live',
        'cta_secondary_label': 'Host Session',
        'cta_secondary_href': '/live?new=1',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'cta',
        'eyebrow': 'Start Your Journey',
        'heading': 'Your learning starts here',
        'heading_secondary': '',
        'subhead': '',
        'body': 'Create your free account, explore courses with Guest Preview, and '
                'begin your journey toward academic excellence.',
        'cta_primary_label': 'Create free account',
        'cta_primary_href': '/signup',
        'cta_secondary_label': 'Browse as guest',
        'cta_secondary_href': '/courses',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'courses_hero',
        'eyebrow': 'Courses',
        'heading': 'Discover the Right Course for Your',
        'heading_secondary': 'Learning Journey.',
        'subhead': 'Explore expertly designed courses with structured lessons, live '
                   'classes, quizzes, assignments and progress tracking — all in one '
                   'place.',
        'body': '',
        'cta_primary_label': 'Explore Courses',
        'cta_primary_href': '',
        'cta_secondary_label': 'Browse Categories',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    # ── /about page — About2.jsx (was 100% hardcoded; see HomeSection's
    #    ABOUT_* docstring in content/models.py). The hero badge's junk
    #    string "DONT HACK US !!" (About2.jsx:59) is deliberately replaced
    #    with the real brand tagline used elsewhere on the site — every
    #    other string below is verbatim.
    {   'section': 'about_hero',
        'eyebrow': 'Empowerment Through Education',
        'heading': 'About',
        'heading_secondary': 'Us',
        'subhead': 'Through innovative technology, our intelligent platform empowers '
                   'individuals to achieve their full potential and contribute '
                   'positively to society.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'about_vision',
        'eyebrow': 'Vision',
        'heading': 'Our',
        'heading_secondary': 'Vision',
        'subhead': 'At ShikshaCom, our vision is to provide learners with the skills '
                   'and knowledge they need to thrive in the modern world. We aim to '
                   'make education accessible, engaging, and effective for everyone, '
                   'regardless of their background or location.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {'list_label': 'Key Initiatives:'},
        'is_active': True},
    {   'section': 'about_mission',
        'eyebrow': 'Mission',
        'heading': 'Our',
        'heading_secondary': 'Mission',
        'subhead': 'At ShikshaCom, our mission is to deliver high-quality, accessible '
                   'education using innovative technology and expert guidance. We are '
                   'committed to empowering learners of all ages and backgrounds to '
                   'achieve their full potential.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
    {   'section': 'about_values',
        'eyebrow': 'Values',
        'heading': 'Our',
        'heading_secondary': 'Value',
        'subhead': 'At ShikshaCom, our values are the foundation of everything we do. '
                   'These values guide our decisions and inspire our team to create a '
                   'positive impact in the world of education.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {   'list_label': 'Our Core Values:',
                     'list_label_secondary': 'Digital Mode of Learning:'},
        'is_active': True},
    {   'section': 'about_why',
        'eyebrow': 'Why Us',
        'heading': 'Why Choose',
        'heading_secondary': 'ShikshaCom?',
        'subhead': 'At ShikshaCom, we offer a unique learning experience designed to '
                   'meet the needs of modern learners. Choose ShikshaCom for '
                   'education that is effective, enjoyable, and accessible from '
                   'anywhere.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True}]

# HomeListItem -- repeatable cards/chips within a section.
LIST_ITEMS = [   {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'live',
        'title': 'Live & recorded classes',
        'subtitle': '',
        'body': 'Attend interactive live classes or revisit recorded lessons and '
                'revise at your own pace.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'coral',
        'order': 0,
        'is_active': True},
    {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'faculty',
        'title': 'Expert faculty',
        'subtitle': '',
        'body': 'Learn from experienced educators and subject mentors who know the '
                'syllabus inside out.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'blue',
        'order': 1,
        'is_active': True},
    {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'board',
        'title': 'Board & exam focused',
        'subtitle': '',
        'body': 'Courses aligned to CBSE, NCERT and MBSE, plus tracks for national '
                'competitive exams.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'green',
        'order': 2,
        'is_active': True},
    {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'flexible',
        'title': 'Flexible learning',
        'subtitle': '',
        'body': 'Study anytime, anywhere, on any device — phone, tablet or computer.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'violet',
        'order': 3,
        'is_active': True},
    {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'guest',
        'title': 'Guest preview',
        'subtitle': '',
        'body': 'Explore lessons and course structure before you enrol — no sign-up '
                'required.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'gold',
        'order': 4,
        'is_active': True},
    {   'section': 'why_shiksha',
        'variant': 'default',
        'icon': 'guidance',
        'title': 'Personal guidance',
        'subtitle': '',
        'body': 'Book one-on-one sessions and clear doubts on a schedule that works '
                'for you.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'pink',
        'order': 5,
        'is_active': True},
    {   'section': 'teachers_students',
        'variant': 'default',
        'icon': 'faculty',
        'title': 'Do you want to teach here?',
        'subtitle': '',
        'body': 'Share your knowledge, create and upload your own courses, teach live '
                'or record lessons, and reach learners across the country.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Become a tutor',
        'cta_href': '/faculty/signup',
        'tint': 'violet',
        'order': 0,
        'is_active': True},
    {   'section': 'teachers_students',
        'variant': 'default',
        'icon': 'book',
        'title': 'Do you want to learn here?',
        'subtitle': '',
        'body': 'Preview courses as a guest, enrol in structured programs for your '
                'class or exam, and learn with live classes, recordings and doubt '
                'support.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Start learning',
        'cta_href': '/courses',
        'tint': 'green',
        'order': 1,
        'is_active': True},
    {   'section': 'browse_categories',
        'variant': 'default',
        'icon': 'board',
        'title': 'School Education',
        'subtitle': 'Classes 8–12 · CBSE, NCERT & MBSE',
        'body': '',
        'pills': ['Mathematics', 'Science', 'English', 'Social Studies'],
        'stat_text': 'Board-aligned live & recorded classes',
        'cta_label': 'Explore School Courses',
        'cta_href': '/courses',
        'tint': 'green',
        'order': 0,
        'is_active': True},
    {   'section': 'browse_categories',
        'variant': 'default',
        'icon': 'research',
        'title': 'Competitive Exams',
        'subtitle': 'JEE · NEET · UPSC · Banking',
        'body': '',
        'pills': ['IIT-JEE', 'NEET', 'UPSC', 'SSC'],
        'stat_text': 'Expert mentors & proven strategies',
        'cta_label': 'Start Exam Prep',
        'cta_href': '/courses',
        'tint': 'blue',
        'order': 1,
        'is_active': True},
    {   'section': 'browse_categories',
        'variant': 'default',
        'icon': 'skills',
        'title': 'Skill & Career',
        'subtitle': 'Olympiads · CA · Coding & more',
        'body': '',
        'pills': ['Olympiads', 'CA Foundation', 'Coding', 'Career'],
        'stat_text': 'Beyond academics — build real skills',
        'cta_label': 'View Programs',
        'cta_href': '/skill/browse',
        'tint': 'gold',
        'order': 2,
        'is_active': True},
    {   'section': 'why_choose',
        'variant': 'default',
        'icon': 'board',
        'title': 'Structured, board-aligned learning',
        'subtitle': '',
        'body': 'Concept-clear courses for Classes 8–12, aligned to CBSE, NCERT and '
                'MBSE.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'coral',
        'order': 0,
        'is_active': True},
    {   'section': 'why_choose',
        'variant': 'default',
        'icon': 'live',
        'title': 'Live classes with recorded revision',
        'subtitle': '',
        'body': 'Attend live for real-time guidance, then rewatch lessons anytime you '
                'need them.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'violet',
        'order': 1,
        'is_active': True},
    {   'section': 'why_choose',
        'variant': 'default',
        'icon': 'guidance',
        'title': 'Personal doubt clearing & guidance',
        'subtitle': '',
        'body': 'Book one-on-one sessions and get support on a schedule that fits you.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'green',
        'order': 2,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'forum',
        'title': 'Community Forum',
        'subtitle': '',
        'body': 'Connect with fellow learners, ask questions and join discussions.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Visit forum',
        'cta_href': '/forum',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'counselling',
        'title': 'Counselling',
        'subtitle': '',
        'body': 'Get academic and career guidance to choose the right path.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Get guidance',
        'cta_href': '/counselling',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'skills',
        'title': 'Skill Development',
        'subtitle': '',
        'body': 'Practical courses to build skills beyond the syllabus.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Explore skills',
        'cta_href': '/skill-development',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'placement',
        'title': 'Placement & Opportunities',
        'subtitle': '',
        'body': 'Stay informed about placements and career opportunities.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'View opportunities',
        'cta_href': '/placements',
        'tint': '',
        'order': 3,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'library',
        'title': 'Explore Library',
        'subtitle': '',
        'body': 'Access notes, study materials, eBooks, previous year papers, guides '
                'and curated learning resources in one place.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Explore Library',
        'cta_href': '/explore',
        'tint': '',
        'order': 4,
        'is_active': True},
    {   'section': 'resources',
        'variant': 'default',
        'icon': 'research',
        'title': 'Research Hub',
        'subtitle': '',
        'body': 'Discover research papers, journals, articles, case studies and '
                'curated academic resources for deeper learning.',
        'pills': [],
        'stat_text': '',
        'cta_label': 'Explore Research',
        'cta_href': '/explore?tab=research',
        'tint': '',
        'order': 5,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'marquee_chip',
        'icon': 'screen',
        'title': 'HD Video Meetings',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'green',
        'order': 0,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'marquee_chip',
        'icon': 'screen',
        'title': 'Screen Sharing',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'blue',
        'order': 1,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'marquee_chip',
        'icon': 'chat',
        'title': 'Live Chat',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'violet',
        'order': 2,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'marquee_chip',
        'icon': 'secure',
        'title': 'Secure Collaboration',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'gold',
        'order': 3,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'stat_chip',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': 'Education',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'stat_chip',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': 'Business',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'stat_chip',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': 'Communities',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'collaborate',
        'variant': 'stat_chip',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': 'Workshops',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 3,
        'is_active': True},
    # ── /about page — About2.jsx. `body` holds the bullet/pillar text (not
    #    `title`) because several bullets exceed HomeListItem.title's
    #    120-char limit; raw hex colours from missionPillars are mapped to
    #    design-token keys in `tint` (teal/green/gold) since the model
    #    forbids raw colours. The "01".."04" numbering on whyFeatures is
    #    NOT stored -- the frontend derives it from `order + 1`.
    {   'section': 'about_vision',
        'variant': 'default',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Leveraging technology like online learning platforms, mobile '
                'schools, and digital resources to reach students in remote areas.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'about_vision',
        'variant': 'default',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Enabling individuals in remote areas to acquire knowledge and '
                'skills for personal growth.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'about_vision',
        'variant': 'default',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Supporting learners of all backgrounds, abilities, and learning '
                'styles.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'about_vision',
        'variant': 'default',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Raising awareness of non-traditional and diverse career '
                'opportunities.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 3,
        'is_active': True},
    {   'section': 'about_vision',
        'variant': 'default',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Bringing the classroom to your doorstep.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 4,
        'is_active': True},
    {   'section': 'about_mission',
        'variant': 'pillar',
        'icon': 'users',
        'title': 'Fostering a supportive community',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'teal',
        'order': 0,
        'is_active': True},
    {   'section': 'about_mission',
        'variant': 'pillar',
        'icon': 'wrench',
        'title': 'Leveraging cutting-edge tools',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'green',
        'order': 1,
        'is_active': True},
    {   'section': 'about_mission',
        'variant': 'pillar',
        'icon': 'sprout',
        'title': 'Making education inclusive, effective, and transformative',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'teal',
        'order': 2,
        'is_active': True},
    {   'section': 'about_mission',
        'variant': 'pillar',
        'icon': 'home',
        'title': 'Bridging the gap in educational access between urban and rural '
                 'settings',
        'subtitle': '',
        'body': '',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': 'gold',
        'order': 3,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'default',
        'icon': '',
        'title': 'Commitment to Excellence',
        'subtitle': '',
        'body': 'Ensures we deliver the highest quality education.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'default',
        'icon': '',
        'title': 'Quality',
        'subtitle': '',
        'body': 'In our content and services empowers learners to succeed.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'default',
        'icon': '',
        'title': 'Inclusivity',
        'subtitle': '',
        'body': 'Welcomes and supports learners from all backgrounds.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'default',
        'icon': '',
        'title': 'Innovation',
        'subtitle': '',
        'body': 'Drives us to continuously improve and adapt.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 3,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'bullet',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Aims to enhance teaching and learning through technology '
                'integration.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'bullet',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Mobile schools bring education directly to remote communities.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'about_values',
        'variant': 'bullet',
        'icon': '',
        'title': '',
        'subtitle': '',
        'body': 'Highly interactive platforms for accessible digital education.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'about_why',
        'variant': 'numbered',
        'icon': '',
        'title': 'Interactive Courses',
        'subtitle': '',
        'body': 'Engage students with multimedia content, quizzes, and real-world '
                'projects.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'about_why',
        'variant': 'numbered',
        'icon': '',
        'title': 'Live Classes',
        'subtitle': '',
        'body': 'Direct interaction with expert instructors, fostering a '
                'supportive learning environment.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'about_why',
        'variant': 'numbered',
        'icon': '',
        'title': 'Personalized Dashboards',
        'subtitle': '',
        'body': 'Track your progress and get content tailored to your learning '
                'pace and goals.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'about_why',
        'variant': 'numbered',
        'icon': '',
        'title': 'Vibrant Community',
        'subtitle': '',
        'body': 'Connect with peers, share knowledge, and grow together in a '
                'thriving forum.',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 3,
        'is_active': True}]

# HomeFloater -- decorative badges in fixed, pre-tested CSS slots.
FLOATERS = [   {   'section': 'hero',
        'slot': 'cap',
        'icon': 'cap',
        'label': '',
        'sublabel': '',
        'is_active': True},
    {   'section': 'hero',
        'slot': 'book',
        'icon': 'book',
        'label': '',
        'sublabel': '',
        'is_active': True},
    {   'section': 'hero',
        'slot': 'play',
        'icon': 'play',
        'label': '',
        'sublabel': '',
        'is_active': True},
    {   'section': 'why_choose',
        'slot': 'b_tl',
        'icon': 'live',
        'label': 'Live + Recorded',
        'sublabel': '',
        'is_active': True},
    {   'section': 'why_choose',
        'slot': 'b_tr',
        'icon': 'folder',
        'label': '17+ Programs',
        'sublabel': 'Classes 8–12 & more',
        'is_active': True},
    {   'section': 'why_choose',
        'slot': 'b_bl',
        'icon': 'check',
        'label': 'Guest preview',
        'sublabel': 'Free · no sign-up',
        'is_active': True},
    {   'section': 'collaborate',
        'slot': 'top',
        'icon': '',
        'label': 'Live now',
        'sublabel': '',
        'is_active': True},
    {   'section': 'collaborate',
        'slot': 'bottom',
        'icon': 'globe',
        'label': 'Available for everyone',
        'sublabel': '',
        'is_active': True}]

# FAQItem -- 6 homepage + 4 legacy /faq page.
FAQS = [   {   'page': 'home',
        'question': 'How do I enroll in a course?',
        'answer_html': '<p>Create a free account, choose the program that matches your '
                       'class or exam, and enroll in a few steps. You can preview '
                       "lessons as a guest first if you'd like to explore before "
                       'signing up.</p>',
        'order': 0,
        'is_active': True},
    {   'page': 'home',
        'question': 'Can I preview courses before enrolling?',
        'answer_html': '<p>Yes. Guest Preview lets you explore sample lessons and '
                       'course structure without creating an account, so you can see '
                       'the teaching style before you commit.</p>',
        'order': 1,
        'is_active': True},
    {   'page': 'home',
        'question': 'Are live classes recorded?',
        'answer_html': '<p>Every live class is recorded and added to your dashboard, '
                       'so you can revisit lessons anytime and revise at your own '
                       'pace.</p>',
        'order': 2,
        'is_active': True},
    {   'page': 'home',
        'question': 'Which boards do you support?',
        'answer_html': '<p>Courses are aligned with CBSE and NCERT, and we support the '
                       'Mizoram Board (MBSE) for learners across Northeast India. More '
                       'boards are on the way.</p>',
        'order': 3,
        'is_active': True},
    {   'page': 'home',
        'question': 'What competitive exams do you prepare students for?',
        'answer_html': '<p>Our competitive tracks cover IIT-JEE, NEET, UPSC and Civil '
                       'Services, and government recruitment exams such as SSC and '
                       'Banking, with more categories being added.</p>',
        'order': 4,
        'is_active': True},
    {   'page': 'home',
        'question': 'Can I learn on my mobile phone?',
        'answer_html': '<p>Yes. ShikshaCom works on any device — phone, tablet or '
                       'computer — so you can attend live classes and watch recordings '
                       'wherever you are.</p>',
        'order': 5,
        'is_active': True},
    {   'page': 'general',
        'question': 'What courses does the coaching provide?',
        'answer_html': '<p>We provide courses for competitive exams, school subjects, '
                       'and professional skill development — including JEE, NEET, '
                       'board exam prep, and more.</p>',
        'order': 0,
        'is_active': True},
    {   'page': 'general',
        'question': 'How can I join the classes?',
        'answer_html': '<p>You can register directly on our website or contact our '
                       'support team for a guided onboarding. Both live and offline '
                       'options are available.</p>',
        'order': 1,
        'is_active': True},
    {   'page': 'general',
        'question': 'Do you offer online classes?',
        'answer_html': '<p>Yes, we offer both live interactive sessions and recorded '
                       'lectures you can revisit anytime — accessible from any '
                       'device.</p>',
        'order': 2,
        'is_active': True},
    {   'page': 'general',
        'question': 'What is the refund policy?',
        'answer_html': '<p>Refund requests must be raised within 24 hours from the '
                       'date of purchase. Please refer to our refund policy page for '
                       'detailed terms and conditions.</p>',
        'order': 3,
        'is_active': True}]

# ShowcaseCourse -- the 18 "Featured courses" cards.
SHOWCASE = [   {   'title': 'Class 8 Foundation',
        'level_label': 'Foundation',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(15,157,107,0.72),rgba(11,91,62,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1560785496-3c9d27877182?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '',
        'link_state': {},
        'order': 0,
        'is_active': True},
    {   'title': 'Class 9 Foundation',
        'level_label': 'Foundation',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(20,184,160,0.72),rgba(11,91,62,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1517971129774-8a2b38fa128e?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '',
        'link_state': {},
        'order': 1,
        'is_active': True},
    {   'title': 'Class 10 Foundation',
        'level_label': 'Foundation',
        'ribbon': 'Bestseller',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(255,178,29,0.72),rgba(242,140,15,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '',
        'link_state': {},
        'order': 2,
        'is_active': True},
    {   'title': 'Class 11 · Science',
        'level_label': 'Science',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(255,122,69,0.72),rgba(225,77,42,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1694230155228-cdde50083573?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'flask',
        'link_path': '',
        'link_state': {},
        'order': 3,
        'is_active': True},
    {   'title': 'Class 11 · Commerce',
        'level_label': 'Commerce',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(124,92,252,0.72),rgba(75,52,199,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'calc',
        'link_path': '',
        'link_state': {},
        'order': 4,
        'is_active': True},
    {   'title': 'Class 11 · Arts',
        'level_label': 'Arts',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(236,78,134,0.72),rgba(193,58,104,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1585661417298-8236a5f449aa?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '',
        'link_state': {},
        'order': 5,
        'is_active': True},
    {   'title': 'Class 12 · Science',
        'level_label': 'Science',
        'ribbon': 'New',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(15,157,107,0.72),rgba(20,184,160,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'flask',
        'link_path': '',
        'link_state': {},
        'order': 6,
        'is_active': True},
    {   'title': 'Class 12 · Commerce',
        'level_label': 'Commerce',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(255,178,29,0.72),rgba(224,139,18,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'calc',
        'link_path': '',
        'link_state': {},
        'order': 7,
        'is_active': True},
    {   'title': 'Class 12 · Arts',
        'level_label': 'Arts',
        'ribbon': '',
        'fact_line': '1 Year · Online · Full access',
        'price_label': '1,500',
        'tutor_name': '',
        'is_explore_card': False,
        'categories': ['class8-12'],
        'gradient_css': 'rgba(59,130,246,0.72),rgba(29,78,216,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1514369118554-e20d93546b30?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '',
        'link_state': {},
        'order': 8,
        'is_active': True},
    {   'title': 'CBSE (Central Board)',
        'level_label': 'National Board',
        'ribbon': 'Popular',
        'fact_line': 'Expert Faculty · Classes 8–12',
        'price_label': '',
        'tutor_name': '',
        'is_explore_card': True,
        'categories': ['boards'],
        'gradient_css': 'rgba(15,157,107,0.72),rgba(11,91,62,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1741699428220-65f37f3fbbcb?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'book',
        'link_path': '/courses',
        'link_state': {'selectedBoardGroup': 'central', 'selectedBoard': 'cbse'},
        'order': 9,
        'is_active': True},
    {   'title': 'Regional Boards',
        'level_label': 'Regional',
        'ribbon': '',
        'fact_line': 'MBSE & more',
        'price_label': '',
        'tutor_name': '',
        'is_explore_card': True,
        'categories': ['boards'],
        'gradient_css': 'rgba(20,184,160,0.72),rgba(11,91,62,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1598981457915-aea220950616?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'compass',
        'link_path': '/courses',
        'link_state': {'selectedBoardGroup': 'state', 'selectedBoard': 'mbse'},
        'order': 10,
        'is_active': True},
    {   'title': 'NEET Preparation',
        'level_label': 'Medical',
        'ribbon': 'Popular',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'Dr. D. Ralte',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(236,78,134,0.72),rgba(193,58,104,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'pulse',
        'link_path': '',
        'link_state': {},
        'order': 11,
        'is_active': True},
    {   'title': 'UPSC & Civil Services',
        'level_label': 'Civil Services',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'K. Zoramthanga',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(255,178,29,0.72),rgba(242,140,15,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1554475900-0a0350e3fc7b?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'institution',
        'link_path': '',
        'link_state': {},
        'order': 12,
        'is_active': True},
    {   'title': 'IIT-JEE Preparation',
        'level_label': 'Engineering',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'A. Sharma',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(124,92,252,0.72),rgba(75,52,199,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1614283226124-5a2f0f23752b?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'target',
        'link_path': '',
        'link_state': {},
        'order': 13,
        'is_active': True},
    {   'title': 'Government Exams',
        'level_label': 'SSC · Banking',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'T. Lalhmingthanga',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(20,184,160,0.72),rgba(11,91,62,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'bank',
        'link_path': '',
        'link_state': {},
        'order': 14,
        'is_active': True},
    {   'title': 'Defence Exams',
        'level_label': 'NDA · CDS',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'Maj. R. Singh (Retd.)',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(59,130,246,0.72),rgba(29,78,216,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1590821091890-bdcc3c1e2b37?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'shield',
        'link_path': '',
        'link_state': {},
        'order': 15,
        'is_active': True},
    {   'title': 'CA Program',
        'level_label': 'Accountancy',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'CA V. Malsawma',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(15,157,107,0.72),rgba(20,184,160,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'calc',
        'link_path': '',
        'link_state': {},
        'order': 16,
        'is_active': True},
    {   'title': 'Olympiad & Foundation',
        'level_label': 'Olympiads',
        'ribbon': '',
        'fact_line': 'Live + Recorded · Launching soon',
        'price_label': '',
        'tutor_name': 'R. Vanlalhriati',
        'is_explore_card': False,
        'categories': ['competitive'],
        'gradient_css': 'rgba(255,122,69,0.72),rgba(225,77,42,0.88)',
        'image_url': 'https://images.unsplash.com/photo-1741699428220-65f37f3fbbcb?w=800&h=400&fit=crop&auto=format&q=75',
        'icon': 'medal',
        'link_path': '',
        'link_state': {},
        'order': 17,
        'is_active': True}]



# ── /contact ──────────────────────────────────────────────────────────────
# Appended as separate constants rather than edited into the pprint-formatted
# lists above, so this stays readable and diffable.
#
# These are the exact strings Contact.jsx hardcoded (its <h1>, its blurb, and
# the four cards), lifted verbatim so seeding changes nothing visible — it just
# moves them somewhere an editor can reach. Bodies keep their <br /> line breaks;
# `br` is in the restricted inline allowlist both server-side
# (content/sanitize.py) and client-side (utils/sanitizeInline.js).
CONTACT_BLOCKS = [
    {   'section': 'contact_hero',
        'eyebrow': '',
        'heading': 'Contact ShikshaCom',
        'heading_secondary': '',
        'subhead': 'Get in touch with us! Here is how you can reach ShikshaCom.',
        'body': '',
        'cta_primary_label': '',
        'cta_primary_href': '',
        'cta_secondary_label': '',
        'cta_secondary_href': '',
        'image_url': '',
        'extra': {},
        'is_active': True},
]

# One row per card. Being list items rather than four fixed slots is the point:
# an office or a phone number can be added or retired without a deploy.
CONTACT_LIST_ITEMS = [
    {   'section': 'contact_hero',
        'variant': 'contact_card',
        'icon': 'location',
        'title': 'Head Office',
        'subtitle': '',
        'body': 'House No. - 1473A<br />Maruti Vihar<br />Gurgaon, Haryana - 122002',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 0,
        'is_active': True},
    {   'section': 'contact_hero',
        'variant': 'contact_card',
        'icon': 'location',
        'title': 'Regional Office Address',
        'subtitle': '',
        'body': 'Hualngohmun Vengchhak<br />Near World Bank Road<br />Aizawl , Mizoram - 796005',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 1,
        'is_active': True},
    {   'section': 'contact_hero',
        'variant': 'contact_card',
        'icon': 'email',
        'title': 'Email',
        'subtitle': '',
        'body': 'info@shikshacom.com',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 2,
        'is_active': True},
    {   'section': 'contact_hero',
        'variant': 'contact_card',
        'icon': 'phone',
        'title': 'Phone',
        'subtitle': '',
        'body': '+0124-4255138 (Haryana)<br />+0389-2300225 (Mizoram)<br />+91 3893570403 (Mizoram)',
        'pills': [],
        'stat_text': '',
        'cta_label': '',
        'cta_href': '',
        'tint': '',
        'order': 3,
        'is_active': True},
]

BLOCKS = BLOCKS + CONTACT_BLOCKS
LIST_ITEMS = LIST_ITEMS + CONTACT_LIST_ITEMS
