# Generated by hand — the skills app shipped without any migrations.
# Covers all 9 models in skills/models.py.

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0012_passwordresetcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. SkillCategory ────────────────────────────────────────────────
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, max_length=8)),
                ("color", models.CharField(blank=True, max_length=9)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["order", "label"],
            },
        ),

        # ── 2. ExpertProfile ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "teacher_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_profile",
                        to="accounts.teacherprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experts",
                        to="skills.skillcategory",
                    ),
                ),
                ("headline", models.CharField(max_length=160)),
                ("skill_tags", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("availability", models.CharField(blank=True, max_length=120)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="skills/experts/")),
                ("hourly_rate", models.PositiveIntegerField(default=0, help_text="Paise (₹1 = 100)")),
                ("rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("sessions_count", models.PositiveIntegerField(default=0)),
                ("is_listed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "-sessions_count"],
            },
        ),
        migrations.AddIndex(
            model_name="expertprofile",
            index=models.Index(fields=["is_listed", "category"], name="skills_expe_is_list_idx"),
        ),

        # ── 3. TeacherApplication ────────────────────────────────────────────
        migrations.CreateModel(
            name="TeacherApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skills.skillcategory",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("track", models.CharField(
                    choices=[("GUEST", "Guest expert (skills)"), ("FACULTY", "Faculty (academic)")],
                    default="GUEST",
                    max_length=10,
                )),
                ("skill_name", models.CharField(max_length=200)),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("experience", models.CharField(blank=True, max_length=40)),
                ("method_note", models.TextField(blank=True)),
                ("skill_tags", models.JSONField(blank=True, default=list)),
                ("intro_video", models.FileField(blank=True, null=True, upload_to="skills/applications/videos/")),
                ("status", models.CharField(
                    choices=[
                        ("submitted", "Submitted"),
                        ("eligibility", "Eligibility check"),
                        ("scheduled", "Interview scheduled"),
                        ("ready", "Ready for interview"),
                        ("approved", "Approved"),
                        ("hold", "On hold"),
                        ("rejected", "Rejected"),
                    ],
                    default="submitted",
                    max_length=20,
                )),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="teacherapplication",
            index=models.Index(fields=["status", "track"], name="skills_teac_status_track_idx"),
        ),

        # ── 4. InterviewSlot ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="InterviewSlot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("starts_at", models.DateTimeField()),
                ("duration_mins", models.PositiveIntegerField(default=30)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("booked_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),

        # ── 5. Interview ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="skills.teacherapplication",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skills.interviewslot",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("meeting_url", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(
                    choices=[
                        ("scheduled", "Scheduled"),
                        ("completed", "Completed"),
                        ("no_show", "No show"),
                    ],
                    default="scheduled",
                    max_length=12,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),

        # ── 6. Evaluation ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="skills.interview",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("scores", models.JSONField(blank=True, default=dict)),
                ("decision", models.CharField(
                    choices=[
                        ("approve", "Approve"),
                        ("hold", "Hold"),
                        ("reject", "Reject"),
                    ],
                    max_length=10,
                )),
                ("recommended_tier", models.CharField(
                    blank=True,
                    choices=[
                        ("standard", "Standard"),
                        ("senior", "Senior"),
                        ("expert", "Expert"),
                    ],
                    max_length=10,
                )),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),

        # ── 7. SkillSession ──────────────────────────────────────────────────
        migrations.CreateModel(
            name="SkillSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "learner_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_sessions",
                        to="accounts.learnerprofile",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="skills.expertprofile",
                    ),
                ),
                ("contact_mode", models.CharField(
                    choices=[
                        ("message", "Message"),
                        ("session", "Session request"),
                        ("video", "Video call"),
                    ],
                    default="session",
                    max_length=10,
                )),
                ("status", models.CharField(
                    choices=[
                        ("requested", "Requested"),
                        ("pending_payment", "Pending payment"),
                        ("confirmed", "Confirmed"),
                        ("completed", "Completed"),
                        ("cancelled", "Cancelled"),
                    ],
                    default="requested",
                    max_length=20,
                )),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("duration_mins", models.PositiveIntegerField(default=60)),
                ("amount", models.PositiveIntegerField(default=0, help_text="Paise")),
                ("note", models.TextField(blank=True)),
                ("meeting_url", models.CharField(blank=True, max_length=300)),
                ("payment_status", models.CharField(
                    choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                    default="unpaid",
                    max_length=10,
                )),
                ("razorpay_order_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="skillsession",
            index=models.Index(fields=["status", "payment_status"], name="skills_sess_status_payment_idx"),
        ),

        # ── 8. Conversation ──────────────────────────────────────────────────
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "learner_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_threads",
                        to="accounts.learnerprofile",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="skills.expertprofile",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=["learner_profile", "expert"],
                name="unique_thread_per_learner_expert",
            ),
        ),

        # ── 9. Message ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="skills.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
