# Generated by Django 6.0.1 on 2026-05-29 12:42

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialfile_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfile',
            name='file',
            field=models.FileField(upload_to='study_materials/', validators=[materials.validators.validate_material_file]),
        ),
    ]
