# Generated by Django 6.0.1 on 2026-07-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_class_level_course_kind_course_status_and_more'),
        ('materials', '0004_materialfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.batch'),
        ),
    ]
