# Generated by Django 6.0.1 on 2026-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_studymaterial_chapter_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
