# Generated by Django 6.0.1 on 2026-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('forum', '0002_tag_reply_reply_to_forumpost_tags'),
        ('forum', '0003_notification'),
    ]

    operations = [
    ]
