# Generated by Django 6.0.1 on 2026-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_solved_views_profile'),
        ('forum', '0005_delete_notification'),
    ]

    operations = [
    ]
