# Generated by Django 6.0.1 on 2026-07-16 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0008_forumpost_kind_forumprofile_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='ban_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutoRejectedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('question', 'Question'), ('post', 'Post'), ('answer', 'Answer'), ('comment', 'Comment')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
                ('categories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('restored', 'Restored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_auto_rejected', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_rejected_children', to='forum.forumpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='forum_autor_status_c1c54b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dismiss', 'Dismiss'), ('delete', 'Delete'), ('warn', 'Warn'), ('ban', 'Ban'), ('unban', 'Unban'), ('restore', 'Restore')], max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_mod_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_mod_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='forum_moder_action_2d7ec4_idx'), models.Index(fields=['target_user'], name='forum_moder_target__162b62_idx')],
            },
        ),
    ]
