# Generated by Django 6.0.1 on 2026-07-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_forumprofile_ban_reason_forumprofile_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
