# Generated by Django 6.0.1 on 2026-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_report_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('dismiss', 'Dismiss'), ('delete', 'Delete'), ('warn', 'Warn'), ('ban', 'Ban'), ('unban', 'Unban'), ('restore', 'Restore'), ('suspend', 'Suspend'), ('lock', 'Lock'), ('unlock', 'Unlock')], max_length=10),
        ),
    ]
