# Generated by Django 6.0.1 on 2026-07-16

from django.db import migrations, models


SEED_CATEGORIES = [
    {"slug": "career",     "name": "Career Guidance",          "description": "Choosing paths, switching fields, and long-term planning.",       "initials": "CG", "color": "#125027", "topic": "Career Guidance",          "order": 0},
    {"slug": "eng",        "name": "Engineering Admissions",   "description": "JEE, counselling, branch vs college and cut-offs.",               "initials": "EA", "color": "#0f8f7e", "topic": "Engineering Admissions",   "order": 1},
    {"slug": "abroad",     "name": "Study Abroad",             "description": "Applications, visas, funding and life overseas.",                 "initials": "SA", "color": "#6b58d3", "topic": "Study Abroad",             "order": 2},
    {"slug": "exams",      "name": "Competitive Exams",        "description": "GATE, UPSC, CAT and other national exams.",                       "initials": "CE", "color": "#ff8f01", "topic": "Competitive Exams",        "order": 3},
    {"slug": "placements", "name": "Placements & Internships", "description": "Resumes, interviews, campus and off-campus roles.",               "initials": "PI", "color": "#c0446b", "topic": "Placements & Internships", "order": 4},
    {"slug": "skills",     "name": "Skill Development",        "description": "Upskilling, projects and self-study roadmaps.",                   "initials": "SD", "color": "#8a5a00", "topic": "Skill Development",        "order": 5},
    {"slug": "scholar",    "name": "Scholarships",             "description": "Grants, assistantships and funding routes.",                      "initials": "SC", "color": "#2f6db5", "topic": "Scholarships",             "order": 6},
    {"slug": "design",     "name": "Design Portfolios",        "description": "NID/NIFT prep, portfolios and creative careers.",                 "initials": "DP", "color": "#a23e9c", "topic": "Design Portfolios",        "order": 7},
]


def seed_categories(apps, schema_editor):
    ForumCategory = apps.get_model("forum", "ForumCategory")
    for row in SEED_CATEGORIES:
        ForumCategory.objects.update_or_create(slug=row["slug"], defaults=row)


def unseed_categories(apps, schema_editor):
    ForumCategory = apps.get_model("forum", "ForumCategory")
    ForumCategory.objects.filter(slug__in=[row["slug"] for row in SEED_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_forumpost_is_locked_forumpost_is_removed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('initials', models.CharField(blank=True, default='', max_length=4)),
                ('color', models.CharField(blank=True, default='#125027', max_length=9)),
                ('topic', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name_plural': 'forum categories',
            },
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
