# Generated by Django 6.0.1 on 2026-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_forumcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
