# Generated by Django 6.0.1 on 2026-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_reply_is_removed_reply_removed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='target_type',
            field=models.CharField(choices=[('space', 'Space'), ('question', 'Question'), ('category', 'Category'), ('user', 'User')], max_length=12),
        ),
    ]
