# Generated by Django 6.0.6 on 2026-06-20 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Chain after the teacher-password migration so the accounts app is
        # fully migrated first. (Chat doesn't use teacher_password directly.)
        ('accounts', '0013_teacherprofile_teacher_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DIRECT', 'Direct (1:1)'), ('COURSE', 'Course room')], max_length=10)),
                ('course_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('direct_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'course_id'], name='chat_conver_kind_145ccc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'DIRECT')), fields=('direct_key',), name='unique_direct_conversation'), models.UniqueConstraint(condition=models.Q(('kind', 'COURSE')), fields=('course_id',), name='unique_course_conversation')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('LEARNER', 'Learner profile'), ('TEACHER', 'Teacher identity')], max_length=10)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('learner_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='accounts.learnerprofile')),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='chat.participant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['learner_profile'], name='chat_partic_learner_9942b0_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['teacher_profile'], name='chat_partic_teacher_be00fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'LEARNER')), fields=('conversation', 'learner_profile'), name='unique_learner_per_conversation'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'TEACHER')), fields=('conversation', 'teacher_profile'), name='unique_teacher_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'client_id'], name='chat_messag_convers_36ea2f_idx'),
        ),
    ]
