# PLACEMENT: backend/backend/chat/migrations/0003_message_client_id_dedupe.py   (NEW FILE)
# DEPLOY:    /app/shiksha-backend/chat/migrations/0003_message_client_id_dedupe.py
#
# M0 (Phase 3 architecture, §25/§32): adds the unique constraint that makes
# at-least-once WebSocket delivery actually idempotent. Hand-written rather
# than autogenerated — `makemigrations` in an environment on a different
# Django patch version recomputes index-name hashes for the whole app and
# proposes renaming 0002_block's indexes, which is unrelated noise, not a
# real change. This migration only adds the one constraint below.
#
# Safe to run on an existing table: NULL client_id rows ("") are excluded by
# the partial condition, so no pre-existing data can violate it.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_block"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=["conversation", "sender", "client_id"],
                condition=~models.Q(client_id=""),
                name="unique_message_client_id_per_sender",
            ),
        ),
    ]
