# Generated by Django 6.0.1 on 2026-06-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_block'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='block',
            new_name='chat_block_blocker_71b343_idx',
            old_name='chat_block_blocker_l_idx',
        ),
        migrations.RenameIndex(
            model_name='block',
            new_name='chat_block_blocker_0fc64a_idx',
            old_name='chat_block_blocker_t_idx',
        ),
        migrations.RenameIndex(
            model_name='block',
            new_name='chat_block_blocked_265f0d_idx',
            old_name='chat_block_blocked_l_idx',
        ),
        migrations.RenameIndex(
            model_name='block',
            new_name='chat_block_blocked_1fba3e_idx',
            old_name='chat_block_blocked_t_idx',
        ),
    ]
