# Generated by Django 6.0.1 on 2026-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chat_block_blocker_l_idx_chat_block_blocker_71b343_idx_and_more'),
        ('chat', '0007_outbox_event'),
    ]

    operations = [
    ]
