# Generated by Django 6.0.1 on 2026-07-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge_20260714_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
