# Generated by Django 6.0.1 on 2026-07-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_merge_20260706_2301'),
        ('chat', '0010_messageattachment_expires_at'),
    ]

    operations = [
    ]
