# Generated by Django 6.0.1 on 2026-04-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_board_sessionrecording_stream_videoprogress_and_more'),
        ('livestream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='livesession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='teacher_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WAITING_FOR_TEACHER', 'Waiting for Teacher'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RECONNECTING', 'Reconnecting')], default='SCHEDULED', max_length=30),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['teacher_left_at'], name='livestream__teacher_0681b2_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course', 'start_time'], name='livestream__course__cbfb88_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['subject', 'start_time'], name='livestream__subject_ef3161_idx'),
        ),
        migrations.AddIndex(
            model_name='livesessionattendance',
            index=models.Index(fields=['session', 'joined_at'], name='livestream__session_e3f22f_idx'),
        ),
    ]
