# Generated by Django 6.0.1 on 2026-05-29 12:42

import assignments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignmentsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-supplied UUID that prevents duplicate creation on accidental double-submit. Optional but recommended.', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=assignments.models.assignment_file_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
