# Generated by Django 6.0.1 on 2026-06-19 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('SELF', 'Account holder'), ('DEPENDENT', 'Dependent / child')], default='SELF', max_length=10)),
                ('pin', models.CharField(blank=True, max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='learners/photos/')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='learners/avatar/')),
                ('avatar_emoji', models.CharField(blank=True, max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city_town', models.CharField(blank=True, max_length=150)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_phone', models.CharField(blank=True, max_length=15)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('currently_studying', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('current_class', models.CharField(blank=True, choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=20)),
                ('board', models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('mbse', 'Mizoram Board of School Education'), ('nios', 'NIOS'), ('other', 'Other State Board')], max_length=20)),
                ('board_other', models.CharField(blank=True, max_length=150)),
                ('school_name', models.CharField(blank=True, max_length=250)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('highest_education', models.CharField(blank=True, choices=[('below_8', 'Below Class 8'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10)),
                ('reason_not_studying', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='accounts_pa_user_id_13d348_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='accounts_pa_ticket_ac9d3f_idx',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.CharField(choices=[('GUEST', 'Guest expert (skills)'), ('FACULTY', 'Faculty (academic)'), ('BOTH', 'Both')], default='FACULTY', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tier',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['account', 'is_active'], name='accounts_le_account_8cde17_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('account',), name='one_default_learner_per_account'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
