# Generated by Django 6.0.1 on 2026-06-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_teacher_password'),
        ('accounts', '0015_teacher_track_status'),
    ]

    operations = [
    ]
