# Generated by Django 6.0.1 on 2026-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260621_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
