# Generated by Django 6.0.1 on 2026-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_teacherprofile_signed_agreement'),
        ('accounts', '0017_restore_teacher_password'),
    ]

    operations = [
    ]
