# Generated by Django 6.0.1 on 2026-07-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_academy_rejection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agreementletterversion',
            new_name='accounts_ag_letter__eefc48_idx',
            old_name='accounts_ag_letter__idx',
        ),
    ]
