# Generated by Django 6.0.1 on 2026-07-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260626_1621'),
        ('accounts', '0020_academy_rejection'),
    ]

    operations = [
    ]
