# Generated by Django 6.0.1 on 2026-07-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_academy_rejection'),
    ]

    # No-op: this was a duplicate of prod's 0022_rename_accounts_ag_letter__idx_
    # accounts_ag_letter__eefc48_idx, which performs the identical RenameIndex and
    # is the one applied on prod. Both branches independently generated the same
    # rename; keeping both would double-rename (the second fails: index already
    # renamed). Prod's 0022 does the real DB rename (in the graph for fresh installs
    # too); this node is kept only to preserve dependency history.
    operations = []
