# Generated by Django 6.0.1 on 2026-07-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_0016_merge_20260626_1621_0020_academy_rejection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agreementletterversion',
            new_name='accounts_ag_letter__eefc48_idx',
            old_name='accounts_ag_letter__idx',
        ),
    ]
