# PLACEMENT: backend/backend/accounts/migrations/0023_teacherprofile_phone.py
# DEPLOY:    /app/shiksha-backend/accounts/migrations/0023_teacherprofile_phone.py
#
# Adds the SMS-reachable mobile to TeacherProfile (see
# notifications/phone.py). Hand-trimmed from Django 6's autogenerated
# migration: the autodetector also proposed cosmetic RenameIndex ops for
# pre-existing indexes (a Django-version naming artifact, nothing to do
# with this change) — those were dropped so this migration is exactly the
# schema change and nothing else.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_populate_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
