# Generated by Django 6.0.1 on 2026-07-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_populate_identity'),
        ('accounts', '0022_rename_accounts_ag_letter__idx_accounts_ag_letter__eefc48_idx'),
    ]

    operations = [
    ]
