# Generated by Django 6.0.1 on 2026-07-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260705_1839'),
        ('accounts', '0023_teacherprofile_phone'),
    ]

    operations = [
    ]
