# Generated by Django 6.0.1 on 2026-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20260714_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('GUEST', 'Guest'), ('MODERATOR', 'Moderator')], max_length=20, unique=True),
        ),
    ]
