# Generated by Django 6.0.1 on 2026-07-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_seed_documents_rbac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teacher_password',
        ),
    ]
