# Generated by Django 6.0.1 on 2026-07-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20260706_2301'),
        ('accounts', '0028_seed_documents_rbac'),
    ]

    operations = [
    ]
