# Generated by Django 6.0.1 on 2026-07-27 19:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_teacherprofile_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=30)),
                ('active_days', models.JSONField(blank=True, default=list)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminders_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goal', to='accounts.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending purge'), ('cancelled', 'Cancelled (account restored)'), ('purged', 'Purged')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('purge_after', models.DateTimeField()),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'purge_after'], name='idx_acctdel_due')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_agent', models.TextField(blank=True)),
                ('browser_label', models.CharField(blank=True, max_length=60)),
                ('platform_label', models.CharField(blank=True, max_length=60)),
                ('device_kind', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='idx_usersession_user_live')],
            },
        ),
    ]
