# Generated by Django 6.0.1 on 2026-07-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_merge_20260718_0040'),
        ('accounts', '0029_remove_teacherprofile_teacher_password'),
    ]

    operations = [
    ]
