# Generated by Django 6.0.1 on 2026-08-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_20260723_2032'),
        ('accounts', '0030_settings_surface'),
    ]

    operations = [
    ]
