# Generated by Django 6.0.1 on 2026-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_merge_0030_merge_20260723_2032_0030_settings_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
