# Generated by Django 6.0.1 on 2026-08-17 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_accepted_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tours', models.JSONField(blank=True, default=dict)),
                ('autoplay_enabled', models.BooleanField(default=True)),
                ('last_auto_tour_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_dismissals', models.PositiveSmallIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('prev_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['identity_key'], name='idx_tourstate_identity')],
            },
        ),
    ]
