# Generated by Django 6.0.1 on 2026-08-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_tourstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='agreement_signer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='signed_agreement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='signed_agreement_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
