# Generated by Django 6.0.1 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_teacherprofile_agreement_signer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourseapplication',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('environmental_science', 'Environmental Science'), ('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('sanskrit', 'Sanskrit'), ('urdu', 'Urdu'), ('other_language', 'Other language'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('philosophy', 'Philosophy'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('commerce', 'Commerce'), ('statistics', 'Statistics'), ('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('general_studies', 'General Studies'), ('general_knowledge', 'General Knowledge'), ('current_affairs', 'Current Affairs'), ('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('public_administration', 'Public Administration'), ('ethics', 'Ethics & Integrity'), ('law', 'Law'), ('physical_education', 'Physical Education'), ('art', 'Art & Craft'), ('music', 'Music'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='skill_related_subject',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('environmental_science', 'Environmental Science'), ('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('sanskrit', 'Sanskrit'), ('urdu', 'Urdu'), ('other_language', 'Other language'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('philosophy', 'Philosophy'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('commerce', 'Commerce'), ('statistics', 'Statistics'), ('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('general_studies', 'General Studies'), ('general_knowledge', 'General Knowledge'), ('current_affairs', 'Current Affairs'), ('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('public_administration', 'Public Administration'), ('ethics', 'Ethics & Integrity'), ('law', 'Law'), ('physical_education', 'Physical Education'), ('art', 'Art & Craft'), ('music', 'Music'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('environmental_science', 'Environmental Science'), ('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('sanskrit', 'Sanskrit'), ('urdu', 'Urdu'), ('other_language', 'Other language'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('philosophy', 'Philosophy'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('commerce', 'Commerce'), ('statistics', 'Statistics'), ('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('general_studies', 'General Studies'), ('general_knowledge', 'General Knowledge'), ('current_affairs', 'Current Affairs'), ('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('public_administration', 'Public Administration'), ('ethics', 'Ethics & Integrity'), ('law', 'Law'), ('physical_education', 'Physical Education'), ('art', 'Art & Craft'), ('music', 'Music'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherskillapplication',
            name='skill_related_subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('environmental_science', 'Environmental Science'), ('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('sanskrit', 'Sanskrit'), ('urdu', 'Urdu'), ('other_language', 'Other language'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('philosophy', 'Philosophy'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('commerce', 'Commerce'), ('statistics', 'Statistics'), ('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('general_studies', 'General Studies'), ('general_knowledge', 'General Knowledge'), ('current_affairs', 'Current Affairs'), ('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('public_administration', 'Public Administration'), ('ethics', 'Ethics & Integrity'), ('law', 'Law'), ('physical_education', 'Physical Education'), ('art', 'Art & Craft'), ('music', 'Music'), ('other', 'Other')], max_length=50),
        ),
    ]
