# Generated by Django 6.0.1 on 2026-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_teachercourseapplication_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementletterversion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='agreements/letters/'),
        ),
    ]
