# Generated by Django 6.0.1 on 2026-08-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_agreementletterversion_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementletterversion',
            options={'ordering': ['-version_number', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='agreementletterversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agreementletterversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Drafts are mutable and hidden from applicants.', max_length=10),
        ),
        migrations.AlterField(
            model_name='agreementletterversion',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agreementletterversion',
            constraint=models.UniqueConstraint(fields=('letter', 'version_number'), name='uniq_agreement_letter_version_number'),
        ),
        migrations.AddConstraint(
            model_name='agreementletterversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('letter',), name='uniq_agreement_letter_single_draft'),
        ),
    ]
