# Generated by Django 6.0.1 on 2026-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_agreementletterversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourseapplication',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='skill_related_subject',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherskillapplication',
            name='skill_related_subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science (general)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('political_science', 'Political Science'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('other', 'Other')], max_length=50),
        ),
    ]
