# Generated by Django 6.0.1 on 2026-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_teachercourseapplication_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='auto_suggest_questions',
            field=models.BooleanField(default=True),
        ),
    ]
