# Generated by Django 6.0.1 on 2026-09-05 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_teacherprofile_auto_suggest_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email_at_link', models.EmailField(max_length=254)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google identity',
                'verbose_name_plural': 'Google identities',
                'indexes': [models.Index(fields=['sub'], name='accounts_go_sub_ee480a_idx')],
            },
        ),
    ]
