# Generated by Django 6.0.1 on 2026-09-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_googleidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
