# Generated by Django 6.0.1 on 2026-09-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_teacherprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_context',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.learnerprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_track',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
