# Generated by Django 6.0.1 on 2026-04-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_fullname_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('computer_science', 'Computer Science'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('political_science', 'Political Science'), ('other', 'Other')], max_length=50)),
                ('boards', models.JSONField(default=list)),
                ('classes', models.JSONField(default=list)),
                ('streams', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSkillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_description', models.CharField(max_length=500)),
                ('skill_related_subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('hindi', 'Hindi'), ('social_science', 'Social Science'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('computer_science', 'Computer Science'), ('accountancy', 'Accountancy'), ('business_studies', 'Business Studies'), ('political_science', 'Political Science'), ('other', 'Other')], max_length=50)),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='teachers/skills/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_applications', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
