# Generated by Django 6.0.1 on 2026-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_13d348_idx',
            old_name='accounts_pa_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_ticket_ac9d3f_idx',
            old_name='accounts_pa_ticket_idx',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
