# Generated by Django 6.0.1 on 2026-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacherprofile_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
