# Generated by Django 6.0.1 on 2026-09-11 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_fix_category_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), models.Q(('file_hash', ''), _negated=True)), fields=('owner', 'file_hash'), name='documents_unique_owner_file_hash'),
        ),
    ]
