# Generated by Django 6.0.1 on 2026-03-12 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_sessionrecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
