# Generated by Django 6.0.1 on 2026-03-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_sessionrecording_videoprogress'),
        ('courses', '0007_videoprogress'),
    ]

    operations = [
    ]
