# Generated by Django 6.0.1 on 2026-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_sessionrecording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price in paise (₹1 = 100 paise)'),
        ),
    ]
