# Generated by Django 6.0.1 on 2026-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_subscription_duration_days'),
        ('courses', '0010_sessionrecording_live_session'),
    ]

    operations = [
    ]
