# Generated by Django 6.0.1 on 2026-05-29 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_board_description_board_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='covered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_covered',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked by a teacher once this chapter has been taught.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Max active students; leave blank for unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive batches are hidden from new enrollments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
            ],
            options={
                'ordering': ['-year', 'code'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='courses_bat_course__2dd092_idx'), models.Index(fields=['year'], name='courses_bat_year_896e15_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'code'), name='unique_batch_code_per_course')],
            },
        ),
    ]
