# Generated by Django 6.0.1 on 2026-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20260326_0827'),
        ('courses', '0013_chapter_covered_at_chapter_is_covered_and_more'),
    ]

    operations = [
    ]
