# Generated by Django 6.0.1 on 2026-07-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_batchchapterprogress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchchapterprogress',
            new_name='courses_bat_batch_i_43bfaa_idx',
            old_name='batch_chapter_covered_idx',
        ),
    ]
