# Generated by Django 6.0.1 on 2026-07-17 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_batch_chapter_covered_idx_courses_bat_batch_i_43bfaa_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('ACADEMIC', 'Academy'), ('COACHING', 'Coaching')], db_index=True, default='ACADEMIC', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='courses.batch'),
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary teacher'), ('ASSISTANT', 'Assistant'), ('SUBSTITUTE', 'Substitute')], default='PRIMARY', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='courses.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='courses.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='courses_tea_teacher_2276eb_idx'), models.Index(fields=['batch', 'subject', 'is_active'], name='courses_tea_batch_i_6bc2bd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('batch', 'subject', 'teacher'), name='uniq_active_teacher_per_batch_subject'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'PRIMARY')), fields=('batch', 'subject'), name='uniq_active_primary_per_batch_subject')],
            },
        ),
    ]
