# Generated by Django 6.0.1 on 2026-07-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_backfill_batch_delivery'),
        ('livestream', '0005_livesession_actual_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='livestream.livesession'),
        ),
    ]
