# Generated by Django 6.0.1 on 2026-07-27 11:47

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_sessionrecording_live_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='price_override',
            field=models.PositiveIntegerField(blank=True, help_text='Paise; overrides Course.price for this batch. Leave blank to use the course price.', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text="Chapter notes/content as HTML. Sanitized on save unless 'trusted html' is ticked."),
        ),
        migrations.AddField(
            model_name='chapter',
            name='trusted_html',
            field=models.BooleanField(default=False, help_text='Skip HTML sanitization — only for first-party content.'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Cover image shown on course cards and the course detail hero (16:9).', null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='textbook',
            field=models.CharField(blank=True, default='', help_text="Textbook reference shown under the subject, e.g. 'Our Pasts III'.", max_length=200),
        ),
    ]
