# Generated by Django 6.0.1 on 2026-07-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_batch_price_override_chapter_content_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
