# Generated by Django 6.0.1 on 2026-07-28 11:17

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_recordingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('group', models.CharField(choices=[('boards', 'Boards'), ('class8-12', 'Class 8-12'), ('competitive', 'Competitive')], max_length=20)),
                ('blurb', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Board logo shown on board cards / filters.', null=True, upload_to='boards/logos/'),
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mrp',
            field=models.PositiveIntegerField(blank=True, help_text='Original/list price in paise (₹1 = 100 paise); shown struck-through against price.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='promo_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='highlights',
            field=models.TextField(blank=True, default='', help_text="One item per line — the 'What you'll learn' list."),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='includes',
            field=models.TextField(blank=True, default='', help_text="One item per line — the 'This course includes' list."),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('COMING_SOON', 'Coming Soon')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.coursecategory'),
        ),
    ]
