# Generated by Django 6.0.1 on 2026-07-28 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_course_slug_alter_board_slug_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNotifyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='courses.board')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('board', 'email'), name='unique_notify_per_board_email')],
            },
        ),
    ]
