# Generated by Django 6.0.1 on 2026-08-10 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_boardnotifyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotifyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'email'), name='unique_notify_per_course_email')],
            },
        ),
    ]
