# Generated by Django 6.0.1 on 2026-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_teachingassignment_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('STATE', 'State'), ('CENTRAL', 'Central'), ('COMPETITIVE', 'Competitive exam')], max_length=20),
        ),
    ]
