# Generated by Django 6.0.1 on 2026-08-23 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_teachercourseapplication_subject_and_more'),
        ('courses', '0033_pendingvideoupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='accounts.learnerprofile'),
        ),
        migrations.AddConstraint(
            model_name='videoprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', False)), fields=('learner_profile', 'recording'), name='uniq_videoprogress_profile_recording'),
        ),
        migrations.AddConstraint(
            model_name='videoprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', True)), fields=('student', 'recording'), name='uniq_videoprogress_account_recording'),
        ),
    ]
