# Generated by Django 6.0.1 on 2026-08-23 20:15
#
# DATA migration. 0034 added VideoProgress.learner_profile so two siblings on
# one parent account stop sharing a single watch position (audit theme T2).
# Every row that predates it has learner_profile = NULL, i.e. it is keyed on
# the ACCOUNT — and the views now look rows up by (account, active profile),
# so without this backfill every existing learner would silently restart every
# recording at 0:00 and lose their "Watched" flags.
#
# Attribution rule: the account's DEFAULT learner profile. That is the same
# rule the rest of this codebase already applies to profile-less legacy rows
# (see the `_dual_key_q` handling for legacy enrollments), and it is the only
# defensible guess — the row records who *the account* was watching as, before
# profiles were distinguishable.
#
# Deliberately NOT backfilled:
#   · accounts with no default learner profile (teachers reviewing their own
#     recordings, staff). Those rows stay account-keyed with NULL, which is
#     exactly the shape the teacher read path now uses.
#   · anything that would collide with an existing (profile, recording) row.
#     None can exist today — the pre-0034 constraint was unique on
#     (student, recording) and a default profile is unique per account — but
#     the guard turns a would-be IntegrityError mid-deploy into a skipped row.
#
# Reverse is a no-op that clears the column back to NULL: it restores the old
# account-keyed shape without inventing data.

from django.db import migrations


def backfill(apps, schema_editor):
    VideoProgress = apps.get_model("courses", "VideoProgress")
    LearnerProfile = apps.get_model("accounts", "LearnerProfile")

    defaults_by_account = {
        p.account_id: p.id
        for p in LearnerProfile.objects.filter(is_default=True, is_active=True)
    }
    if not defaults_by_account:
        return

    existing = set(
        VideoProgress.objects.filter(learner_profile__isnull=False)
        .values_list("learner_profile_id", "recording_id")
    )

    seen = set()
    safe = []
    for row in VideoProgress.objects.filter(learner_profile__isnull=True):
        profile_id = defaults_by_account.get(row.student_id)
        if profile_id is None:
            continue
        key = (profile_id, row.recording_id)
        if key in seen or key in existing:
            continue
        seen.add(key)
        row.learner_profile_id = profile_id
        safe.append(row)

    if safe:
        VideoProgress.objects.bulk_update(safe, ["learner_profile"], batch_size=500)


def unbackfill(apps, schema_editor):
    VideoProgress = apps.get_model("courses", "VideoProgress")
    VideoProgress.objects.update(learner_profile=None)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0034_alter_videoprogress_unique_together_and_more"),
        # LearnerProfile is read above; without this the historical model may
        # not exist yet on a fresh database.
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
