# Generated by Django 6.0.1 on 2026-08-24 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Chapter provenance fields + the generic ContentChapterTag join.

    ON THE is_custom BACKFILL — DELIBERATELY NOT GUESSED
    ────────────────────────────────────────────────────
    Every existing Chapter row keeps the field default, is_custom=False, and
    this migration does NOT try to infer which of them were teacher-typed.

    That inference is not available. The shipped
    ``courses.services.resolve_or_create_chapter()`` path (live since
    2026-08-24, used by Create-assignment, Upload-material and the quiz
    builder) writes a plain Chapter row with no marker distinguishing it from
    one an admin authored as part of the curated syllabus. Any heuristic
    available here — order==0, created_at, a null marked_by — is also true of
    large numbers of genuine syllabus chapters, so guessing would relabel real
    curriculum as teacher scratch work in the admin's review queue. A false
    negative (a teacher-typed chapter shown as curated) is recoverable by an
    admin; a false positive is a corrupted syllabus.

    From this migration forward the distinction is recorded accurately at
    creation time: resolve_or_create_chapter() stamps is_custom=True on rows
    it actually creates.
    """

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0035_backfill_videoprogress_learner_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The teacher who typed this chapter, for is_custom rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_custom',
            field=models.BooleanField(db_index=True, default=False, help_text='Typed by a teacher rather than authored as part of the curated syllabus.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContentChapterTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('custom_label', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_tags', to='courses.chapter')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='courses_con_content_c83538_idx'), models.Index(fields=['chapter'], name='courses_con_chapter_93f44e_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'chapter', 'custom_label'), name='uniq_chapter_tag_per_object'), models.UniqueConstraint(condition=models.Q(('chapter__isnull', True)), fields=('content_type', 'object_id', 'custom_label'), name='uniq_freetext_chapter_tag_per_object')],
            },
        ),
    ]
