# Generated by Django 6.0.1 on 2026-08-28 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_backfill_content_chapter_tags'),
        ('livestream', '0010_livesession_chapter_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='trim_end_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrecording',
            name='trim_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sessionrecording',
            constraint=models.CheckConstraint(condition=models.Q(('trim_start_seconds__isnull', True), ('trim_end_seconds__isnull', True), ('trim_end_seconds__gt', models.F('trim_start_seconds')), _connector='OR'), name='sessionrecording_trim_window_valid'),
        ),
    ]
