# Generated by Django 6.0.1 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_sessionrecording_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="auto_record_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="Record this course's live classes automatically. Leave unset to follow the global default. Egress is billed per minute.",
                null=True,
            ),
        ),
    ]
