# Generated by Django 6.0.1 on 2026-09-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_sessionrecording_trim_end_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('school', 'School Education'), ('competitive', 'Competitive Exams'), ('skill', 'Skill & Career')], db_index=True, max_length=16)),
                ('heading', models.CharField(blank=True, default='', help_text='Groups links under a sub-heading. Leave blank for a flat list.', max_length=60)),
                ('label', models.CharField(max_length=60)),
                ('href', models.CharField(blank=True, default='', help_text='Used when no course is picked, e.g. /skill/browse', max_length=300)),
                ('soon', models.BooleanField(default=False, help_text='Show as an inert “Coming Soon” row.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, help_text='Link to a real course — survives a rename.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_menu_links', to='courses.course')),
            ],
            options={
                'verbose_name': 'Navbar menu link',
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
