# Generated by Django 6.0.1 on 2026-09-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_navmenulink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('STATE', 'State'), ('CENTRAL', 'National'), ('COMPETITIVE', 'Competitive exam')], max_length=20),
        ),
    ]
