# Generated by Django 6.0.1 on 2026-07-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_idempotency_key_assignmentfile'),
        ('courses', '0017_course_class_level_course_kind_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.batch'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['batch', 'due_date'], name='assignments_batch_i_48baf4_idx'),
        ),
    ]
