# Generated by Django 6.0.1 on 2026-07-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_seed_documents_rbac'),
        ('assignments', '0004_assignment_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentsubmission',
            name='unique_assignment_submission',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.learnerprofile'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'learner_profile'], name='assignments_assignm_5117dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', False)), fields=('assignment', 'learner_profile'), name='uniq_submission_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', True)), fields=('assignment', 'student'), name='uniq_submission_legacy_account'),
        ),
    ]
