# Generated by Django 6.0.1 on 2026-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_max_marks_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Unpublished assignments are drafts: invisible to students and silent. Publishing notifies the class.'),
        ),
    ]
