# Generated by Django 6.0.1 on 2026-08-23 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignment_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
