"""Give Assignment an independent subject anchor, then let chapter go null.

WHY BOTH IN ONE MIGRATION
─────────────────────────
These two changes are only safe together. Making `chapter` nullable while
authorization still derived subject/course by walking `chapter.subject` would
mean a NULL chapter produced "no subject", and therefore no staffing check at
all — a privilege-escalation hole, not a cosmetic gap. So the non-null
`subject` column has to exist and be populated in the same transaction that
relaxes `chapter`.

Written by hand rather than autogenerated because a non-nullable FK added to a
populated table needs the three-step add-nullable → backfill → tighten dance;
`makemigrations` would instead prompt for a one-size default.

The backfill is exact, not a guess: `chapter` is non-null for every existing
row (it has been required since 0001_initial), so `chapter.subject_id` is
always available and is by definition the subject the assignment belongs to.

Also flips `chapter` from CASCADE to SET_NULL. Teacher-typed chapter names
became real courses.Chapter rows when custom chapters shipped on 2026-08-24,
which turned an admin tidying a syllabus into a silent mass-delete of the
assignments filed under the removed chapter — and, cascading off Assignment,
their student submissions and grades. Losing a curriculum label when a chapter
is deleted is acceptable; losing graded student work is not.
"""

import django.db.models.deletion
from django.db import migrations, models


def backfill_subject_from_chapter(apps, schema_editor):
    """Copy chapter.subject_id into the new column for every existing row.

    Set-based UPDATE ... FROM via a correlated Subquery rather than a Python
    loop: these are production-sized tables and this runs inside the deploy's
    migrate step.
    """
    Assignment = apps.get_model("assignments", "Assignment")
    Chapter = apps.get_model("courses", "Chapter")

    Assignment.objects.filter(subject__isnull=True).update(
        subject_id=models.Subquery(
            Chapter.objects.filter(pk=models.OuterRef("chapter_id"))
            .values("subject_id")[:1]
        )
    )


def unbackfill(apps, schema_editor):
    """Reverse is a no-op: the column itself is dropped by the AddField's own
    reverse, so there is nothing to undo here. Present so the migration is
    reversible end to end rather than blocking a rollback."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0008_alter_assignmentsubmission_submitted_at"),
        ("courses", "0036_chapter_provenance_and_content_chapter_tag"),
    ]

    operations = [
        # 1. Add nullable, so the column can exist on a populated table.
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.subject",
            ),
        ),
        # 2. Populate it from the chapter that is still guaranteed present.
        migrations.RunPython(backfill_subject_from_chapter, unbackfill),
        # 3. Tighten to NOT NULL — authorization may not hang off a nullable
        #    column.
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.subject",
            ),
        ),
        # 4. Only now is it safe to relax chapter. SET_NULL fixes the
        #    admin-deletes-a-chapter-and-loses-graded-work path.
        migrations.AlterField(
            model_name="assignment",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="courses.chapter",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject"], name="assignments_subject_8f3bbf_idx"
            ),
        ),
    ]
