# Generated by Django 6.0.1 on 2026-07-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_profile_isolation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='activity_ac_user_id_11f1d0_idx',
            old_name='activity_feed_hotpath_idx',
        ),
    ]
