# Generated by Django 6.0.1 on 2026-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_activity_feed_hotpath_idx_activity_ac_user_id_11f1d0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('SESSION', 'Live Session'), ('SUBMISSION', 'Submission'), ('MATERIAL', 'Study Material')], max_length=20),
        ),
    ]
