# Generated by Django 6.0.1 on 2026-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('SESSION', 'Live Session'), ('SUBMISSION', 'Submission'), ('MATERIAL', 'Study Material'), ('RECORDING', 'Recording')], max_length=20),
        ),
    ]
