# Generated by Django 6.0.1 on 2026-08-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
