# Generated by Django 6.0.1 on 2026-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
