# Generated by Django 6.0.1 on 2026-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_time_limit_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
