# Generated by Django 6.0.1 on 2026-03-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_time_limit_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default='Temporary explanation'),
            preserve_default=False,
        ),
    ]
