# Generated by Django 6.0.1 on 2026-03-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_explanation'),
        ('quizzes', '0006_question_explanation'),
    ]

    operations = [
    ]
