# Generated by Django 6.0.1 on 2026-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quiz_quizzes_qui_due_dat_3b60ae_idx_and_more'),
        ('quizzes', '0008_alter_quizattempt_unique_together_and_more'),
    ]

    operations = [
    ]
