# Generated by Django 5.1.15 on 2026-07-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_batch_chapter_covered_idx_courses_bat_batch_i_43bfaa_idx'),
        ('quizzes', '0009_merge_20260630_1651'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Practice — instant feedback'), ('mock', 'Mock test — timed')], default='mock', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='quizzes_que_topic_e323bb_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='quizzes_que_difficu_79adbb_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['review_status'], name='quizzes_qui_review__834203_idx'),
        ),
    ]
