# Generated by Django 6.0.1 on 2026-07-17 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_class_level_course_kind_course_status_and_more'),
        ('quizzes', '0011_backfill_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.batch'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['batch', 'is_published'], name='quizzes_qui_batch_i_4854a5_idx'),
        ),
    ]
