# Generated by Django 6.0.1 on 2026-07-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_seed_documents_rbac'),
        ('quizzes', '0012_quiz_batch_quiz_quizzes_qui_batch_i_4854a5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='unique_attempt_per_number',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='learner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.learnerprofile'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['learner_profile', 'quiz'], name='quizzes_qui_learner_b2b17a_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', False)), fields=('quiz', 'learner_profile', 'attempt_number'), name='uniq_attempt_per_profile_number'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('learner_profile__isnull', True)), fields=('quiz', 'student', 'attempt_number'), name='uniq_attempt_legacy_account_number'),
        ),
    ]
