# Generated by Django 6.0.1 on 2026-07-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_remove_quizattempt_unique_attempt_per_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='due_date',
        ),
    ]
