# Generated by Django 6.0.1 on 2026-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_remove_quiz_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI-drafted'), ('bank', 'From question bank'), ('import', 'Bulk import')], default='manual', max_length=10),
        ),
    ]
