# Generated by Django 6.0.1 on 2026-08-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_backfill_videoprogress_learner_profile'),
        ('quizzes', '0017_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.chapter'),
        ),
    ]
