# Generated by Django 6.0.1 on 2026-08-23 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_backfill_videoprogress_learner_profile'),
        ('quizzes', '0018_add_quiz_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='assigned_quizzes', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_assigned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['batch', 'is_assigned'], name='quizzes_qui_batch_i_a6923e_idx'),
        ),
    ]
