# Generated by Django 6.0.1 on 2026-08-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_backfill_quiz_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bank_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_state',
            field=models.CharField(choices=[('private', 'Kept private'), ('suggested', 'Suggested — awaiting curation'), ('accepted', 'Accepted into the ShikshaCom bank'), ('changes_requested', 'Admin asked for changes')], default='suggested', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='suggest_to_bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank_state'], name='quizzes_que_bank_st_2b8349_idx'),
        ),
    ]
