# Generated by Django 6.0.1 on 2026-08-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_backfill_question_bank_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter_note',
            field=models.TextField(blank=True, help_text="Teacher's note about what this covers. Shown to students."),
        ),
        migrations.AddField(
            model_name='quiz',
            name='no_specific_chapter',
            field=models.BooleanField(default=False, help_text='Teacher explicitly marked this as spanning no particular chapter. Mutually exclusive with chapter tags.'),
        ),
    ]
