# Generated by Django 6.0.1 on 2026-08-24 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_quiz_chapter_note_quiz_no_specific_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marks_per_wrong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reveal_answers',
            field=models.CharField(choices=[('after_each', 'After each question'), ('after_submit', 'After the paper is submitted'), ('never', 'Never')], default='after_each', max_length=16),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizzes.quizsection'),
        ),
        migrations.AddIndex(
            model_name='quizsection',
            index=models.Index(fields=['quiz', 'order'], name='quizzes_qui_quiz_id_206eb2_idx'),
        ),
    ]
