# Generated by Django 6.0.1 on 2026-08-24 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_teacherprofile_auto_suggest_questions'),
        ('courses', '0038_backfill_content_chapter_tags'),
        ('quizzes', '0026_backfill_quiz_reveal_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='courses.chapter')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='accounts.learnerprofile')),
                ('questions', models.ManyToManyField(related_name='practice_sessions', to='quizzes.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='quizzes.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='quizzes.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.practicesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['learner_profile', 'chapter'], name='quizzes_pra_learner_8b9056_idx'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_practice_answer'),
        ),
    ]
