# Generated by Django 6.0.1 on 2026-08-25 07:19

"""Phase 10: drop `Quiz.is_published`, the pre-Phase-1 visibility gate.

DESTRUCTIVE, AND THE REVERSE DOES NOT RESTORE DATA — RemoveField's reverse
re-adds an empty column. Recovery is `is_published = is_assigned`, which is
exact: they were mirrored on every write path, and it was verified on
production that 0 of 8 quizzes disagreed before this ran.

WHY IT IS SAFE
──────────────
Phase 1 moved student visibility onto `is_assigned`; this has been a
write-only mirror since. Every reader was migrated first:
  · TeacherQuizDeleteView's "this quiz has N attempts" confirmation
  · dashboard._teacher_quizzes
  · the Django admin's list_display / list_filter
  · the teacher UI's handleDelete, handleView and draft-status fallback
The teacher frontend shipped to production BEFORE this, on purpose: a dropped
field deserialises as `undefined`, which is falsy, so dropping it first would
have silently disabled the destructive-delete confirmation and routed every
quiz to the draft preview.

The two indexes go with it. Their replacement, (batch, is_assigned), already
existed — every student queryset filters on is_assigned.

WHAT THIS DOES *NOT* DO
───────────────────────
`Quiz.chapter` is still here. Nothing reads it (practice and S3 both use the
`chapter_tags` GenericRelation now, and 0028 made those tags complete), but it
is still WRITTEN by courses/chapter_tags.py's additive invariant at line 318,
which is shared by five models in four apps — and Assignment.chapter is
required, with authorization derived through it. Dropping this column needs
that shared write made model-aware first. That is a change to shared
infrastructure, not a Phase 10 cleanup, so it is deliberately left out.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_backfill_quiz_chapter_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_is_publ_8ea5d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_batch_i_4854a5_idx',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
    ]
