# Generated by Django 6.0.1 on 2026-08-25 07:43

"""Phase 10: drop `Quiz.chapter`, the last legacy chapter FK on Quiz.

DESTRUCTIVE. The reverse re-adds an empty nullable column; the values are not
restored. Recovery is from ContentChapterTag — `primary_chapter()`'s rule is
"the first resolved tag" — which is exactly why 0028 ran first and why this
migration comes after it, not with it.

ORDER THIS DEPENDED ON
──────────────────────
1. 0028 backfilled a tag for every quiz that had the FK, so tags became a
   complete substitute rather than a partial one.
2. The three readers moved onto the `chapter_tags` GenericRelation: practice
   supply, per-chapter graded accuracy, and the practice question pool. S3's
   fallback went too.
3. `courses/chapter_tags.py`'s additive invariant — which wrote this FK on
   every tag write — became model-aware via `has_chapter_fk()`. That mixin
   serves FIVE models in four apps and they retire their FKs independently;
   writing unconditionally would now raise on Quiz.
4. `QuizCreateSerializer.chapter_id` lost `source="chapter"`. The key stays in
   the API because the live QuizBuilder still sends it, but it is resolved in
   validate() and written as a tag by _apply_tags() instead of onto a column.

DOES NOT GENERALISE. `Assignment.chapter` is REQUIRED and the staffing-triangle
check at assignments/serializers.py derives subject and course through it — it
is authorization-bearing and must not be dropped by copying this. Quiz was
safe only because it carries its own `subject` FK.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_drop_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
    ]
