# Generated by Django 6.0.1 on 2026-08-25 08:30

from django.conf import settings
"""Phase 10: drop `Quiz.batch`, the pre-Phase-2 single-batch shim.

DESTRUCTIVE, and the reverse does not restore data. Recovery is from
`batches` — the shim always held `batch_ids[0]` — which is why 0031 runs first.

THE RISK THIS CARRIES, STATED PLAINLY
─────────────────────────────────────
`quizzes/visibility.py` reads an empty `batches` set as "every batch of the
course". While the shim existed, a quiz with the shim set and the M2M empty was
saved by a fallback clause. Remove the column with any such row still around
and that quiz goes course-wide — one batch seeing another batch's test. This is
the one migration in Phase 10 that could leak data rather than just break.

What makes it safe, in order:
  1. `QuizCreateSerializer.create()` now populates `batches` alongside the
     shim. It wrote only the shim before, so every quiz created after 0021
     reintroduced the divergence 0021 had just fixed.
  2. `TeacherQuizDuplicateView` now copies the M2M. It copied only the shim,
     so duplicating a multi-batch quiz produced a copy that was one batch by
     the fallback and would have been course-wide without it.
  3. The assign endpoint already wrote both.
  4. 0031 backfilled any straggler. Measured 0 affected rows on production and
     0 on dev before writing it.
  5. `BatchScopeHasNoLeakWithoutTheLegacyFKTest` asserts the outcome through
     the real student endpoint — a quiz scoped to another batch stays hidden,
     one scoped to mine stays visible, a genuinely course-wide one stays
     visible, and create populates the M2M. It passed with the fallback in
     place AND after it was removed, which is what demonstrates the fallback
     was dead rather than merely unused.

ANY NEW WRITER MUST SET `batches`. There is no shim left to catch it, and the
failure mode is silent over-exposure, not an error.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_backfill_content_chapter_tags'),
        ('quizzes', '0031_backfill_quiz_batches_from_shim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_batch_i_a6923e_idx',
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_assigned'], name='quizzes_qui_is_assi_e04172_idx'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='batch',
        ),
    ]
