# Generated by Django 6.0.1 on 2026-09-06 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_backfill_course_media_usages'),
        ('courses', '0039_sessionrecording_trim_end_seconds_and_more'),
        ('quizzes', '0032_drop_batch_shim'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single correct answer'), ('multi', 'Multiple correct answers (not implemented)'), ('numeric', 'Numeric answer (not implemented)')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Exam year this question is from, when known.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('subject', 'Subject'), ('exam', 'Exam'), ('topic', 'Topic'), ('custom', 'Custom')], db_index=True, max_length=12)),
                ('label', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('live', 'Live — clickable, shows its question count'), ('soon', 'Soon — greyed out, not clickable'), ('hidden', 'Hidden — not rendered at all')], default='soon', help_text="What a visitor sees. Defaults to 'soon' so a newly created subject never appears clickable before it has questions.", max_length=8)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', help_text="Sprite id from the hub's inline SVG sheet, e.g. 'qi-book'.", max_length=40)),
                ('color', models.CharField(blank=True, default='', help_text="Accent hex for the subject card, e.g. '#0F9D6B'.", max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_tag', models.ForeignKey(blank=True, help_text='Optional link to the CMS label of the same name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_tags', to='content.contenttag')),
                ('course', models.ForeignKey(blank=True, help_text="For kind='exam': the competitive-exam Course this names.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_tags', to='courses.course')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Cover art for the recommendation cards, from the CMS library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_tag_covers', to='content.contentimage')),
            ],
            options={
                'ordering': ['kind', 'display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quizzes.questiontag'),
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['kind', 'status'], name='quizzes_que_kind_08e735_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='uniq_question_tag_per_kind'),
        ),
    ]
