# Generated by Django 6.0.1 on 2026-09-06 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0033_question_question_type_question_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_count', models.PositiveSmallIntegerField(default=10, help_text='How many questions to serve, at most.')),
                ('minutes', models.PositiveSmallIntegerField(default=10)),
                ('seed', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft — not on the public site'), ('published', 'Published — anyone can practise it')], default='draft', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sets_by_exam', to='quizzes.questiontag')),
                ('subject_tag', models.ForeignKey(help_text="A kind='subject' tag. Drives both the card and the query.", on_delete=django.db.models.deletion.PROTECT, related_name='practice_sets', to='quizzes.questiontag')),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['status', 'display_order'], name='quizzes_pra_status_f71e4a_idx')],
            },
        ),
    ]
