# Generated by Django 6.0.1 on 2026-09-06 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_practiceset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_attempts', to=settings.AUTH_USER_MODEL)),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quizzes.practiceset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicAttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('selected_text', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.publicattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_attempt_answers', to='quizzes.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_attempt_answers', to='quizzes.choice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='publicattempt',
            index=models.Index(fields=['account', '-started_at'], name='quizzes_pub_account_1bc4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicattempt',
            index=models.Index(fields=['practice_set', 'submitted_at'], name='quizzes_pub_practic_7bf7f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_public_attempt_question'),
        ),
    ]
