# Generated by Django 6.0.1 on 2026-06-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', 'migrations__0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expertprofile',
            new_name='skills_expe_is_list_667347_idx',
            old_name='skills_expe_is_list_idx',
        ),
        migrations.RenameIndex(
            model_name='skillsession',
            new_name='skills_skil_status_b80883_idx',
            old_name='skills_sess_status_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherapplication',
            new_name='skills_teac_status_c00cd2_idx',
            old_name='skills_teac_status_track_idx',
        ),
    ]
