# Generated by Django 6.0.1 on 2026-06-22 10:12
#
# NEUTRALIZED — this migration's operations were a strict subset of the
# sibling migration 0002_skillcourse_skillcourseenrollment_skillcoursesection_and_more
# (same SkillCourse/SkillCourseEnrollment/SkillCourseSection/SkillCourseLecture/
# SkillLectureProgress/ExpertReview cluster; the sibling additionally has
# SkillPaymentRequest). Both were independently generated `makemigrations`
# runs for the same models.py change and later reconciled with a plain
# graph merge (0003_merge_20260623_1124) that never removed the duplicate
# table-creation — so a fresh migrate hit "table skills_skillcourse
# already exists" the moment both branches replayed.
#
# The sibling file is kept as the one authoritative CreateModel source
# (it's the more complete of the two). This file's operations are emptied
# to a pure graph pass-through. Any database where THIS file (rather than
# the sibling) was the one actually applied historically is unaffected —
# Django never re-diffs an already-applied migration's content.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_restore_teacher_password'),
        ('skills', '0001_rename_skills_expe_is_list_idx_skills_expe_is_list_667347_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
