# Generated by Django 6.0.1 on 2026-06-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_courses_reviews'),
        ('skills', '0002_skillcourse_skillcourseenrollment_skillcoursesection_and_more'),
    ]

    operations = [
    ]
