# Generated by Django 6.0.1 on 2026-06-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_expertprofile_availability_slots'),
        ('skills', '0003_merge_20260623_1124'),
    ]

    operations = [
    ]
