# Generated by Django 6.0.1 on 2026-06-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_merge_20260623_1302'),
        ('skills', '0004_skillsession_slot_key'),
    ]

    operations = [
    ]
