# Generated by Django 6.0.1 on 2026-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_merge_20260623_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='availability_slots',
        ),
        migrations.AlterField(
            model_name='skillsession',
            name='slot_key',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
