# Generated by Django 6.0.1 on 2026-06-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_messaging'),
        ('skills', '0006_remove_expertprofile_availability_slots_and_more'),
    ]

    operations = [
    ]
