# Generated by Django 6.0.1 on 2026-06-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_expert_location_advertising_subscription'),
        ('skills', '0007_merge_20260625_1909'),
    ]

    operations = [
    ]
