# Generated by Django 6.0.1 on 2026-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_merge_20260625_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='availability_slots',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly availability. Shape: {"open":["0-1","2-3"], "booked":["1-0"]}'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='class_location',
            field=models.CharField(blank=True, help_text='Exact location text; required when class_mode is home/travel.', max_length=255),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='Approved expert appears in the directory. FREE — never gated by subscription. Gates session/booking visibility, so it must stay True for every approved expert.'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='payment_upi',
            field=models.CharField(blank=True, help_text="Expert's own UPI ID (learners pay here).", max_length=120),
        ),
        migrations.AlterField(
            model_name='skillsession',
            name='slot_key',
            field=models.CharField(blank=True, help_text="Reserved availability slot, e.g. '3-1' (day-slot index).", max_length=16),
        ),
    ]
