# Generated by Django 6.0.1 on 2026-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_skillsession_started_at'),
        ('skills', '0009_expertprofile_availability_slots_and_more'),
    ]

    operations = [
    ]
