# Generated by Django 6.0.1 on 2026-07-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_skillsession_started_at'),
        ('skills', '0010_expertprofile_is_suspended'),
    ]

    operations = [
    ]
