# Generated by Django 6.0.1 on 2026-07-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_expertprofile_categories'),
        ('skills', '0011_merge_20260702_1033'),
    ]

    operations = [
    ]
