# Generated by Django 6.0.1 on 2026-07-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_merge_20260702_2117'),
        ('skills', '0012_merge_skillsession_started_at'),
    ]

    operations = [
    ]
