# Generated by Django 6.0.1 on 2026-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_merge_20260704_0204'),
        ('skills', '0012_merge_skillsession_started_at'),
    ]

    operations = [
    ]
