# Generated by Django 6.0.1 on 2026-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_merge_20260704_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='intro_video_bunny_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='intro_video_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Created'), (1, 'Uploaded'), (2, 'Processing'), (3, 'Transcoding'), (4, 'Finished'), (5, 'Error')], null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='intro_video_thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
