# Generated by Django 6.0.1 on 2026-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_expertprofile_intro_video_bunny_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsession',
            name='proposed_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillsession',
            name='proposed_slot_key',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='skillsession',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skillsession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('needs_reconfirmation', 'Needs reconfirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
