# Generated by Django 6.0.1 on 2026-07-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_merge_20260706_2301'),
        ('skills', '0015_skillsession_proposed_scheduled_for_and_more'),
    ]

    operations = [
    ]
