# Generated by Django 6.0.1 on 2026-07-28 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_skillsession_proposed_scheduled_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMarketingBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('browse_hero', 'Browse page hero'), ('teach_banner', 'Teach my craft banner'), ('hub', 'Hub two-door landing')], max_length=20, unique=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/marketing/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/categories/'),
        ),
    ]
