# Generated by Django 6.0.1 on 2026-07-28 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_skillmarketingblock_skillcategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='skills.skillsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'user'], name='skills_skil_session_fd6014_idx'), models.Index(fields=['session', 'joined_at'], name='skills_skil_session_7b9e39_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SkillSessionAttendanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_reconcile', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_intervals', to='skills.skillsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['session', 'user'], name='skills_skil_session_73d074_idx'), models.Index(fields=['session', 'joined_at'], name='skills_skil_session_33b112_idx'), models.Index(fields=['session', 'left_at'], name='skills_skil_session_64d4c8_idx')],
            },
        ),
    ]
