# Generated by Django 6.0.1 on 2026-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0017_skillsessionattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='mastery_target',
            field=models.PositiveSmallIntegerField(default=3, help_text='Sessions a student must complete with this expert to reach mastery (1-12).'),
        ),
    ]
