# Generated by Django 6.0.1 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_expertprofile_mastery_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('needs_reconfirmation', 'Needs reconfirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('auto_declined', 'Auto-declined (24h SLA)')], default='requested', max_length=20),
        ),
    ]
