# Generated by Django 6.0.1 on 2026-08-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0019_alter_skillsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsession',
            name='status_before_reschedule',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
