# Generated by Django 6.0.1 on 2026-08-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0020_skillsession_status_before_reschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsession',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillsession',
            name='no_show_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
