# Generated by Django 6.0.1 on 2026-08-05 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0021_skillsession_no_show_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertBlackoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='skills.expertprofile')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
    ]
