# Generated by Django 6.0.1 on 2026-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0022_expertblackoutdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='education',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='experience_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
