# Generated by Django 6.0.1 on 2026-08-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0023_expertprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
