# Generated by Django 6.0.1 on 2026-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0024_expertreview_is_edited_expertreview_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsession',
            name='teacher_note',
            field=models.TextField(blank=True),
        ),
    ]
