# Generated by Django 6.0.1 on 2026-08-09 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0025_skillsession_teacher_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('skill_tags', models.JSONField(blank=True, default=list)),
                ('price_paise', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='skills/listings/')),
                ('intro_video_bunny_id', models.CharField(blank=True, max_length=255)),
                ('intro_video_status', models.IntegerField(blank=True, null=True)),
                ('intro_video_thumbnail_url', models.URLField(blank=True)),
                ('mastery_target', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='skills.skillcategory')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='skills.expertprofile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingModerationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('listing_burst', 'More than three listings published in seven days'), ('reported', 'Reported by a user')], max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flags', to='skills.expertprofile')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flags', to='skills.skilllisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='skillsession',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='skills.skilllisting'),
        ),
        migrations.CreateModel(
            name='SkillListingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=8)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_keys', to='skills.skilllisting')),
            ],
        ),
        migrations.AddIndex(
            model_name='skilllisting',
            index=models.Index(fields=['expert', 'is_active'], name='skills_skil_expert__356b85_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllisting',
            index=models.Index(fields=['category', 'is_active'], name='skills_skil_categor_928003_idx'),
        ),
        migrations.AddIndex(
            model_name='listingmoderationflag',
            index=models.Index(fields=['is_open', '-created_at'], name='skills_list_is_open_8569e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skilllistingslot',
            unique_together={('listing', 'slot_key')},
        ),
    ]
