# Generated by Django 6.0.1 on 2026-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0027_seed_skill_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsession',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
