# Generated by Django 6.0.1 on 2026-08-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_merge_20260718_0040'),
        ('skills', '0027_seed_skill_listings'),
    ]

    operations = [
    ]
