# Generated by Django 6.0.1 on 2026-08-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0028_skillsession_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmarketingblock',
            name='stat_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
