# Generated by Django 6.0.1 on 2026-08-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0028_merge_20260810_1627'),
        ('skills', '0029_skillmarketingblock_stat_label'),
    ]

    operations = [
    ]
