# Generated by Django 6.0.1 on 2026-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0030_merge_20260816_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('needs_reconfirmation', 'Needs reconfirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('auto_declined', 'Auto-declined (24h SLA)'), ('lapsed', "Didn't take place")], default='requested', max_length=20),
        ),
    ]
