# Generated by Django 6.0.1 on 2026-09-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0033_remove_evaluation_evaluator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='class_mode',
            field=models.CharField(choices=[('home', 'At my place'), ('travel', 'Home tutor (travels to the learner)'), ('online', 'Online only')], default='online', max_length=10),
        ),
    ]
