# Generated by Django 6.0.1 on 2026-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0033_remove_evaluation_evaluator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='intro_video_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skilllisting',
            name='intro_video_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
