# Generated by Django 4.2.30 on 2026-07-16 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=300)),
                ('link_url', models.CharField(blank=True, default='', help_text='Optional. Internal path (/courses) or full URL.', max_length=300)),
                ('link_label', models.CharField(blank=True, default='', max_length=60)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning')], default='info', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave empty to run indefinitely.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('courses', 'Courses'), ('counselling', 'Counselling'), ('skills', 'Skill Development'), ('general', 'General / FAQ page')], db_index=True, default='general', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer_html', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('level_label', models.CharField(help_text='Chip on the thumbnail, e.g. "Foundation".', max_length=40)),
                ('ribbon', models.CharField(blank=True, default='', help_text='Optional corner ribbon, e.g. "Bestseller".', max_length=20)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('fact_line', models.CharField(default='1 Year · Online · Full access', max_length=80)),
                ('price_label', models.CharField(blank=True, default='', help_text='e.g. "1,500" (₹/month). Empty + tutor set = Coming Soon.', max_length=20)),
                ('tutor_name', models.CharField(blank=True, default='', max_length=80)),
                ('is_explore_card', models.BooleanField(default=False, help_text="Render a single 'Explore Programs' button.")),
                ('categories', models.JSONField(default=list, help_text='Filter tabs this card appears in, e.g. ["class8-12"].')),
                ('gradient_css', models.CharField(default='rgba(15,157,107,0.72),rgba(11,91,62,0.88)', help_text='Two rgba() stops for the thumbnail overlay.', max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/showcase/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Used if no image file is uploaded.')),
                ('icon', models.CharField(choices=[('book', 'Book'), ('flask', 'Flask'), ('calc', 'Calculator')], default='book', max_length=12)),
                ('link_path', models.CharField(blank=True, default='/courses', max_length=200)),
                ('link_state', models.JSONField(blank=True, default=dict, help_text='router state, e.g. {"selectedBoardGroup":"central","selectedBoard":"cbse"}')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Set in the future to schedule publication.')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('affair_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='The date the event/news belongs to (drives grouping).')),
                ('category', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('economy', 'Economy'), ('polity', 'Polity & Governance'), ('science-tech', 'Science & Technology'), ('environment', 'Environment'), ('sports', 'Sports'), ('awards', 'Awards & Persons'), ('misc', 'Miscellaneous')], db_index=True, default='national', max_length=20)),
                ('summary', models.TextField(blank=True, default='', help_text='1–3 sentence summary shown in the list.')),
                ('body_html', models.TextField(blank=True, default='')),
                ('source_name', models.CharField(blank=True, default='', max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('tags', models.ManyToManyField(blank=True, related_name='current_affairs', to='content.contenttag')),
            ],
            options={
                'ordering': ['-affair_date', '-publish_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='content_ca_live_idx'), models.Index(fields=['affair_date', 'category'], name='content_ca_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Set in the future to schedule publication.')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(blank=True, help_text='Path-style, e.g. class-9/economics/chapter-1. Left blank → built from class / subject / chapter.', max_length=220, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens; separate path segments with single slashes (e.g. class-9/economics/chapter-1).', regex='^[a-z0-9]+(?:-[a-z0-9]+)*(?:/[a-z0-9]+(?:-[a-z0-9]+)*)*$')])),
                ('class_level', models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('general', 'General / not class-specific')], db_index=True, default='general', max_length=10)),
                ('subject', models.CharField(choices=[('science', 'Science'), ('mathematics', 'Mathematics'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('civics', 'Civics'), ('political-science', 'Political Science'), ('english', 'English'), ('general', 'General')], db_index=True, default='general', max_length=24)),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, help_text='For chapter-wise study posts; leave empty for articles.', null=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary shown on listing cards (≈1–2 sentences).')),
                ('cover', models.ImageField(blank=True, help_text='Card thumbnail. ~800×450 recommended.', null=True, upload_to='content/blog/%Y/%m/')),
                ('body_html', models.TextField(help_text="Chapter/article body as HTML. Sanitized on save unless 'trusted html' is ticked.")),
                ('trusted_html', models.BooleanField(default=False, help_text='Skip HTML sanitization — only for first-party fragments imported from the legacy extractor.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=70)),
                ('seo_description', models.CharField(blank=True, default='', max_length=170)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='content.contenttag')),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='content_blog_live_idx'), models.Index(fields=['class_level', 'subject'], name='content_blog_taxo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_number__isnull', False)), fields=('class_level', 'subject', 'chapter_number'), name='content_blog_unique_chapter'),
        ),
    ]
