# Generated by Django 6.0.1 on 2026-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Small pill above the heading, e.g. "Trusted by 50,000+ Students".',
                        max_length=80,
                    ),
                ),
                (
                    "heading",
                    models.CharField(help_text='e.g. "Learn Smarter."', max_length=160),
                ),
                (
                    "heading_highlight",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='The emphasised gradient line, e.g. "Achieve More".',
                        max_length=160,
                    ),
                ),
                ("subheading", models.TextField(blank=True, default="")),
                (
                    "primary_cta_text",
                    models.CharField(default="Get Started", max_length=60),
                ),
                (
                    "primary_cta_link",
                    models.CharField(default="/signup", max_length=200),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="content/hero/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Used if no image file is uploaded.",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "Classes 8–12 · CBSE, NCERT & MBSE".',
                        max_length=160,
                    ),
                ),
                (
                    "pills",
                    models.JSONField(
                        default=list,
                        help_text='Short tags shown as chips, e.g. ["Mathematics", "Science"].',
                    ),
                ),
                (
                    "stat_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "Board-aligned live & recorded classes".',
                        max_length=160,
                    ),
                ),
                ("cta_text", models.CharField(default="Explore", max_length=60)),
                ("link_path", models.CharField(default="/courses", max_length=200)),
                ("link_state", models.JSONField(blank=True, default=dict)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("target", "Target"),
                            ("briefcase", "Briefcase"),
                        ],
                        default="school",
                        max_length=12,
                    ),
                ),
                (
                    "gradient",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("warm", "Warm"),
                            ("cool", "Cool"),
                        ],
                        default="green",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "home categories",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeCta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eyebrow", models.CharField(blank=True, default="", max_length=80)),
                ("heading", models.CharField(max_length=160)),
                ("subheading", models.TextField(blank=True, default="")),
                (
                    "primary_text",
                    models.CharField(default="Create free account", max_length=60),
                ),
                ("primary_link", models.CharField(default="/signup", max_length=200)),
                (
                    "secondary_text",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "secondary_link",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "home CTA",
                "verbose_name_plural": "home CTA",
                "ordering": ["order", "id"],
            },
        ),
    ]
