# Generated by Django 6.0.1 on 2026-07-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('courses', '0020_batch_price_override_chapter_content_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecourse',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional link to a real course. When set, link_path/link_state are derived server-side instead of the manual values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_cards', to='courses.course'),
        ),
    ]
