# Generated by Django 6.0.1 on 2026-07-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_showcasecourse_course'),
        ('courses', '0023_coursecategory_board_display_order_board_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecourse',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_cards', to='courses.board'),
        ),
        migrations.AlterField(
            model_name='showcasecourse',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Filter tabs this card appears in, e.g. ["class8-12"].'),
        ),
    ]
