# Generated by Django 6.0.1 on 2026-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_showcasecourse_board_alter_showcasecourse_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA')], db_index=True, max_length=24, unique=True)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=80)),
                ('heading', models.CharField(blank=True, default='', max_length=200)),
                ('heading_secondary', models.CharField(blank=True, default='', help_text='Optional 2nd half of a two-part heading (only Hero uses this today).', max_length=200)),
                ('subhead', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('cta_primary_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_primary_href', models.CharField(blank=True, default='', max_length=200)),
                ('cta_secondary_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_secondary_href', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/home/')),
                ('image_url', models.URLField(blank=True, default='', help_text='Used if no image file is uploaded.')),
                ('extra', models.JSONField(blank=True, default=dict, help_text="Rare escape valve for a section-specific single value that doesn't warrant its own column. Should normally be empty.")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Homepage content block',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='HomeListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA')], db_index=True, max_length=24)),
                ('variant', models.CharField(choices=[('default', 'Default'), ('marquee_chip', 'Marquee chip (Collaborate)'), ('stat_chip', 'Stat chip (Collaborate)')], default='default', max_length=20)),
                ('icon', models.CharField(blank=True, default='', help_text="Icon key from the frontend's shared icon set.", max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('pills', models.JSONField(blank=True, default=list, help_text="Short tag list, e.g. BrowseCategories' subject pills.")),
                ('stat_text', models.CharField(blank=True, default='', max_length=160)),
                ('cta_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_href', models.CharField(blank=True, default='', max_length=200)),
                ('tint', models.CharField(blank=True, default='', help_text='Design-token key (e.g. violet/green/gold) — the frontend maps this to a CSS variable, never a raw color.', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Homepage list item',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFloater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA')], db_index=True, max_length=24)),
                ('slot', models.CharField(max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('sublabel', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Homepage floater',
                'ordering': ['section', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('section', 'slot'), name='content_homefloater_unique_slot')],
            },
        ),
    ]
