# Generated by Django 6.0.1 on 2026-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homecontentblock_homelistitem_homefloater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentblock',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='homefloater',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24),
        ),
    ]
