# Generated by Django 6.0.1 on 2026-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_homecontentblock_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasecourse',
            name='icon',
            field=models.CharField(choices=[('book', 'Book'), ('flask', 'Flask'), ('calc', 'Calculator'), ('compass', 'Compass'), ('pulse', 'Pulse'), ('target', 'Target'), ('bank', 'Bank'), ('shield', 'Shield'), ('medal', 'Medal'), ('institution', 'Institution')], default='book', max_length=12),
        ),
    ]
