# Generated by Django 6.0.1 on 2026-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_showcasecourse_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24, unique=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage section order',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='homefloater',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero')], db_index=True, max_length=24),
        ),
    ]
