# Generated by Django 6.0.1 on 2026-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_seed_homesectionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_html_source',
            field=models.TextField(blank=True, default='', editable=False, help_text="Body as submitted, before sanitization. Kept so a future sanitizer rule change can't destroy authored content the way it silently did before this field existed."),
        ),
    ]
