# Generated by Django 6.0.1 on 2026-08-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='focal_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='focal_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
