# Generated by Django 6.0.1 on 2026-08-14 03:03

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contentimage_alt_text_contentimage_focal_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blogpost',
            name='content_blog_unique_chapter',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], db_index=True, default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, help_text="Path-style, e.g. class-9/economics/chapter-1. Left blank → built from class / subject / chapter. Unique per locale, not globally — a Hindi translation conventionally reuses the same slug as its English sibling, disambiguated by the public URL's /hi/ prefix rather than by the slug string itself.", max_length=220, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens; separate path segments with single slashes (e.g. class-9/economics/chapter-1).', regex='^[a-z0-9]+(?:-[a-z0-9]+)*(?:/[a-z0-9]+(?:-[a-z0-9]+)*)*$')]),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['translation_group'], name='content_blog_transgroup_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['locale', 'status', 'publish_at'], name='content_blog_locale_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_number__isnull', False)), fields=('class_level', 'subject', 'chapter_number', 'locale'), name='content_blog_unique_chapter_locale'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='content_blog_unique_slug_locale'),
        ),
    ]
