# Generated by Django 6.0.1 on 2026-08-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_fix_shared_translation_group_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Block-tree body (shared/src/blogBlocks/schema.js). When non-empty, this is what the public reader actually renders — never body_html. Validated on write against content.blocks.KNOWN_BLOCK_TYPES; permissive on read, so a block type added by a newer frontend build simply contributes no text to reading_minutes on an older one.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_theme',
            field=models.JSONField(blank=True, default=dict, help_text="Palette override for a block-authored post — a subset of the 24 tokens in schema.js's THEME_TOKENS, each a hex color. Travels as plain JSON and is injected into the reader iframe as a <style> block by the frontend; never passed through clean_html(), since the sanitizer's ALLOWED_TAGS has no 'style' tag and would strip it."),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body_html',
            field=models.TextField(help_text="Chapter/article body as HTML. Sanitized on save unless 'trusted html' is ticked. When body_blocks is non-empty this becomes a DERIVED FALLBACK — computed and stored on every save for legacy consumers and non-block-aware code paths, but the public reader treats body_blocks as authoritative and renders from it directly at read time. See shared/src/blogBlocks/render.js."),
        ),
        migrations.CreateModel(
            name='BlogRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_blocks', models.JSONField(blank=True, default=list)),
                ('body_theme', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='content_blo_post_id_444efc_idx')],
            },
        ),
    ]
