# Generated by Django 6.0.1 on 2026-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_homecontentblock_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/home/'),
        ),
        migrations.AddField(
            model_name='homelistitem',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Used if no image file is uploaded.'),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='variant',
            field=models.CharField(choices=[('default', 'Default'), ('marquee_chip', 'Marquee chip (Collaborate)'), ('stat_chip', 'Stat chip (Collaborate)'), ('bullet', 'Bullet (About — secondary list)'), ('pillar', 'Pillar (About — Mission icon row)'), ('numbered', 'Numbered card (About — Why Choose)'), ('sticker', 'Sticker (About — hero image row)')], default='default', max_length=20),
        ),
    ]
