# Generated by Django 6.0.1 on 2026-08-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_homelistitem_image_homelistitem_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasecourse',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='showcasecourse',
            name='stars',
        ),
    ]
