# Generated by Django 6.0.1 on 2026-08-25 17:05

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_showcasecourse_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, help_text='Card thumbnail. ~800×450 recommended.', null=True, upload_to='content/blog/%Y/%m/', validators=[content.validators.CmsImageValidator()]),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='file',
            field=models.ImageField(upload_to='content/editor/%Y/%m/', validators=[content.validators.CmsImageValidator()]),
        ),
        migrations.AlterField(
            model_name='homecontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/home/', validators=[content.validators.CmsImageValidator()]),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/home/', validators=[content.validators.CmsImageValidator()]),
        ),
        migrations.AlterField(
            model_name='showcasecourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/showcase/', validators=[content.validators.CmsImageValidator()]),
        ),
    ]
