# Generated by Django 6.0.1 on 2026-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_blogpost_cover_alter_contentimage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentblock',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='homefloater',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='variant',
            field=models.CharField(choices=[('default', 'Default'), ('marquee_chip', 'Marquee chip (Collaborate)'), ('stat_chip', 'Stat chip (Collaborate)'), ('bullet', 'Bullet (About — secondary list)'), ('pillar', 'Pillar (About — Mission icon row)'), ('numbered', 'Numbered card (About — Why Choose)'), ('sticker', 'Sticker (About — hero image row)'), ('contact_card', 'Contact card (Contact — details)')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='homesectionorder',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24, unique=True),
        ),
    ]
