# Generated by Django 6.0.1 on 2026-08-26 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_homecontentblock_section_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AddField(
            model_name='homecontentblock',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AddField(
            model_name='homefloater',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AddField(
            model_name='homelistitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AddField(
            model_name='showcasecourse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='currentaffair',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content draft',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='content_con_content_13dd5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'author'), name='uniq_contentdraft_object_author')],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('hidden', 'Hidden'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_revisions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content revision',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='content_con_content_6944e7_idx')],
            },
        ),
    ]
