# Generated by Django 6.0.1 on 2026-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_backfill_status_from_is_active'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='content.contentimage')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Picture usage',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='content_med_content_b3377d_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'content_type', 'object_id', 'field_name'), name='uniq_mediausage_asset_target_field')],
            },
        ),
    ]
