# Generated by Django 6.0.1 on 2026-08-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_backfill_media_usages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homecontentblock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homefloater',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homelistitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='showcasecourse',
            name='is_active',
        ),
    ]
