# Generated by Django 6.0.1 on 2026-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_backfill_embedded_media_usages'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecourse',
            name='coming_soon_override',
            field=models.BooleanField(blank=True, help_text='Leave unset to follow the linked course. Set to force the “Coming Soon” badge on or off.', null=True),
        ),
        migrations.AddField(
            model_name='showcasecourse',
            name='use_own_details',
            field=models.BooleanField(default=False, help_text="Use this card's own title, price and picture instead of the linked course's."),
        ),
    ]
