# Generated by Django 6.0.1 on 2026-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_showcasecourse_coming_soon_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stored on cards, and the tab id the homepage filters by. Cannot be "all" — see clean().', max_length=40, unique=True)),
                ('label', models.CharField(help_text='Shown on the tab, e.g. "Class 8–12".', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the tab without untagging any card.')),
            ],
            options={
                'verbose_name': 'showcase category',
                'verbose_name_plural': 'showcase categories',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
