# Generated by Django 6.0.1 on 2026-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_seed_showcase_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentblock',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('about_cta', 'About — Closing CTA'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='homefloater',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('about_cta', 'About — Closing CTA'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homelistitem',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('about_cta', 'About — Closing CTA'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='homesectionorder',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('why_shiksha', 'Why Shiksha'), ('teachers_students', 'Teachers & Students'), ('browse_categories', 'Browse Categories'), ('featured_courses', 'Featured Courses'), ('why_choose', 'Why Choose ShikshaCom'), ('resources', 'Resources & Support'), ('collaborate', 'Collaborate'), ('faq', 'FAQ'), ('cta', 'Closing CTA'), ('courses_hero', 'Courses Hero'), ('about_hero', 'About — Hero'), ('about_vision', 'About — Our Vision'), ('about_mission', 'About — Our Mission'), ('about_values', 'About — Our Values'), ('about_why', 'About — Why Choose ShikshaCom'), ('about_cta', 'About — Closing CTA'), ('contact_hero', 'Contact — Header & details')], db_index=True, max_length=24, unique=True),
        ),
    ]
