# Generated by Django 6.0.1 on 2026-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_alter_homecontentblock_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent or guardian'), ('teacher', 'Teacher or tutor'), ('school', 'School or institution'), ('other', 'Other')], max_length=20)),
                ('topic', models.CharField(choices=[('admissions', 'Admissions & course enquiry'), ('support', 'Student support'), ('partnerships', 'Schools & partnerships'), ('careers', 'Careers at ShikshaCom'), ('feedback', 'Feedback or something else')], max_length=20)),
                ('message', models.TextField()),
                ('consented_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('handled_note', models.TextField(blank=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Contact message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_con_status_9b545f_idx')],
            },
        ),
    ]
