# Generated by Django 6.0.1 on 2026-09-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_newslettersubscriber_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediausage',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
    ]
