# Generated by Django 6.0.1 on 2026-09-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_prune_unknown_showcase_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontentblock',
            name='heading_secondary',
            field=models.CharField(blank=True, default='', help_text='Optional 2nd half of a two-part heading, rendered in the accent colour. Used by hero, featured_courses, faq, courses_hero, contact_hero and the five about_* sections.', max_length=200),
        ),
    ]
