# Generated by Django 6.0.1 on 2026-09-09 22:03

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_alter_homecontentblock_heading_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Optional second line on card slots. The navbar strip ignores it.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/ticker/', validators=[content.validators.CmsImageValidator()]),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Used if no image file is uploaded.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='kind',
            field=models.CharField(blank=True, choices=[('new_course', 'New course'), ('enrolment', 'Enrolment'), ('new_mentor', 'New mentor'), ('practice', 'Practice set'), ('deadline', 'Deadline'), ('milestone', 'Milestone'), ('current_affairs', 'Current affairs'), ('mentor_spotlight', 'Mentor spotlight')], default='', help_text='Card treatment. Required for any slot other than the navbar strip.', max_length=24),
        ),
        migrations.AddField(
            model_name='announcement',
            name='metric_label',
            field=models.CharField(blank=True, default='', help_text='Its unit, e.g. STUDENTS or QUESTIONS.', max_length=24),
        ),
        migrations.AddField(
            model_name='announcement',
            name='metric_value',
            field=models.CharField(blank=True, default='', help_text='The big number on the card, e.g. 2,400. Text, not a number — the design renders thousands separators. Leave empty for a deadline; that one is derived from the end time.', max_length=16),
        ),
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Sorts ahead of everything else in its slots.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='slots',
            field=models.JSONField(blank=True, default=list, help_text='Which surfaces this may appear on. Empty behaves as navbar-only.'),
        ),
    ]
