# Generated by Django 6.0.1 on 2026-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_ticker_band_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', help_text='Draft and In review are invisible to the public. Published is live. Archived is deliberately taken down.', max_length=12)),
                ('key', models.SlugField(help_text='Stable identifier used by the frontend, e.g. signup / login. Changing it re-points whichever card refers to it.', max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('blurb', models.CharField(blank=True, default='', help_text='One line under the title, e.g. “Create your account”.', max_length=120)),
                ('bunny_video_id', models.CharField(blank=True, default='', help_text='Bunny Stream guid. Until this is set the video is hidden from the site even when published.', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Synced from Bunny by `manage.py sync_demo_videos`. Leave blank — anything typed here is overwritten.', null=True)),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Synced from Bunny by `manage.py sync_demo_videos`.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Landing demo video',
                'ordering': ['order', 'id'],
            },
        ),
    ]
