# Generated by Django 6.0.1 on 2026-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_demovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demovideo',
            name='bunny_status',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bunny's encoding status, synced by `manage.py sync_demo_videos`. The site only shows a clip once this reads 4 (Finished) — a guid alone does not mean anything plays. Run the sync after uploading.", null=True),
        ),
    ]
