# PLACEMENT: backend/backend/counseling/migrations/0001_initial.py   (NEW FILE)
# DEPLOY:    /app/shiksha-backend/counseling/migrations/0001_initial.py
#
# NOTE on the accounts dependency: this migration FKs accounts.LearnerProfile.
# On your existing databases that table already exists, so ("accounts",
# "__first__") is sufficient. On a completely fresh database, run
# `python manage.py migrate accounts` before `migrate counseling`.
# Generated by Django 6.0.6 on 2026-07-04 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sections', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], db_index=True, default='confirmed', max_length=12)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('student_note', models.CharField(blank=True, default='', help_text='What the student wants to discuss (shown to the counselor).', max_length=500)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_counseling_appointments', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_counseling_appointments', to=settings.AUTH_USER_MODEL)),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_appointments', to='accounts.learnerprofile')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='counseling.appointment')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_assessments', to='accounts.learnerprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counseling.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='counselors/photos/')),
                ('bio', models.TextField(blank=True, default='')),
                ('qualifications', models.TextField(blank=True, default='')),
                ('certifications', models.TextField(blank=True, default='')),
                ('approach', models.TextField(blank=True, default='', help_text='Counseling approach shown on the public profile.')),
                ('years_experience', models.CharField(blank=True, choices=[('lt1', 'Less than 1 year'), ('1_3', '1-3 years'), ('3_5', '3-5 years'), ('5_10', '5-10 years'), ('10plus', '10+ years')], default='', max_length=10)),
                ('languages', models.CharField(blank=True, default='', max_length=200)),
                ('session_duration_minutes', models.PositiveIntegerField(default=45)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=12)),
                ('is_listed', models.BooleanField(default=True, help_text='Approved counselors can be temporarily hidden from the directory.')),
                ('review_note', models.CharField(blank=True, default='', max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_counselor_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(blank=True, related_name='counselors', to='counseling.specialization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='counseling.counselorprofile'),
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='counseling.appointment')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='counseling.counselorprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('next_steps', models.TextField(blank=True, default='', help_text='Recommended next steps / follow-up plan.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='counselors/reports/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='counseling.appointment')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='counseling.counselorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CounselingIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_industry', models.CharField(blank=True, default='', max_length=150)),
                ('work_environment', models.CharField(blank=True, choices=[('office', 'Office / corporate'), ('field', 'Field work / outdoors'), ('remote', 'Remote / online'), ('creative', 'Creative studio'), ('research', 'Research / academia'), ('public', 'Public service / government'), ('entrepreneur', 'Own business / startup'), ('mixed', 'Mixed / not sure yet')], default='', max_length=20)),
                ('long_term_goals', models.TextField(blank=True, default='')),
                ('short_term_goals', models.TextField(blank=True, default='')),
                ('skills', models.CharField(blank=True, default='', max_length=400)),
                ('languages', models.CharField(blank=True, default='', help_text='Languages the student is comfortable being counseled in.', max_length=200)),
                ('favorite_subjects', models.CharField(blank=True, default='', max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_intake', to='accounts.learnerprofile')),
                ('career_interests', models.ManyToManyField(blank=True, related_name='interested_learners', to='counseling.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='counseling.counselorprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_start_before_end')],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['counselor', 'scheduled_at'], name='counseling__counsel_c58a45_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='counseling__status_4ab441_idx'),
        ),
    ]
