# Generated by Django 6.0.7 on 2026-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
