# Generated by Django 6.0.1 on 2026-08-06 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_showcasecourse_board_alter_showcasecourse_categories'),
        ('counseling', '0003_counselorprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Set in the future to schedule publication.')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('blurb', models.CharField(blank=True, default='', max_length=300)),
                ('audience', models.CharField(max_length=120)),
                ('stage', models.SlugField(max_length=24)),
                ('stage_label', models.CharField(max_length=40)),
                ('stage_order', models.PositiveSmallIntegerField(default=0)),
                ('accent', models.CharField(choices=[('orange', 'Orange'), ('green', 'Green'), ('teal', 'Teal')], default='teal', max_length=12)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='counseling/guides/')),
                ('legacy_slugs', models.JSONField(blank=True, default=list)),
                ('glance', models.JSONField(blank=True, default=list)),
                ('class_levels', models.JSONField(blank=True, default=list, help_text='e.g. ["9", "10"]')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, default='', max_length=70)),
                ('seo_description', models.CharField(blank=True, default='', max_length=170)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('source_filename', models.CharField(blank=True, default='', max_length=200)),
                ('source_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('import_version', models.PositiveSmallIntegerField(default=0)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('specializations', models.ManyToManyField(blank=True, related_name='career_guides', to='counseling.specialization')),
                ('tags', models.ManyToManyField(blank=True, related_name='career_guides', to='content.contenttag')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuideChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('content', 'Content'), ('worksheet', 'Worksheet'), ('action_plan', 'Action plan'), ('parent_guide', 'Parent & guardian guide'), ('faq', 'FAQ'), ('references', 'References')], default='content', max_length=14)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='counseling.careerguide')),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('level', models.PositiveSmallIntegerField(default=2, help_text='1=h1 2=h2 3=h3')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('anchor', models.SlugField(blank=True, default='', max_length=140)),
                ('kind', models.CharField(choices=[('content', 'Content'), ('worksheet', 'Worksheet'), ('action_plan', 'Action plan'), ('parent_guide', 'Parent & guardian guide'), ('faq', 'FAQ'), ('references', 'References')], db_index=True, default='content', max_length=14)),
                ('audience', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent / guardian'), ('teacher', 'Teacher')], db_index=True, default='student', max_length=8)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='counseling.guidechapter')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='counseling.careerguide')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='careerguide',
            index=models.Index(fields=['status', 'publish_at'], name='counseling__status_0db5d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guidechapter',
            unique_together={('guide', 'slug')},
        ),
        migrations.AddIndex(
            model_name='guidesection',
            index=models.Index(fields=['guide', 'order'], name='counseling__guide_i_4856de_idx'),
        ),
    ]
