# Generated by Django 6.0.1 on 2026-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_career_guides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerguide',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12),
        ),
    ]
