# Generated by Django 6.0.1 on 2026-07-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_copy_forum_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notif_recipient_created_idx',
        ),
    ]
