# Generated by Django 6.0.1 on 2026-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_audience_identity'),
        ('notifications', '0003_rename_notif_recipient_read_idx_notificatio_recipie_4e3567_idx_and_more'),
    ]

    operations = [
    ]
