# PLACEMENT: backend/backend/notifications/migrations/0004_multichannel.py
# DEPLOY:    /app/shiksha-backend/notifications/migrations/0004_multichannel.py
#
# NotificationPreference + SmsLog + ReminderLog (multi-channel layer).
# Hand-trimmed: Django 6's autodetector also proposed RenameIndex ops
# for the three pre-existing Notification indexes (version-specific
# index-name normalization, no schema effect) — dropped so this
# migration contains only the new tables.
# Generated by Django 6.0.7 on 2026-07-13 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_audience_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('muted_categories', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('counseling', 'Counseling appointment'), ('private_session', 'Private session'), ('group_session', 'Group session')], max_length=20)),
                ('object_id', models.CharField(max_length=40)),
                ('offset_minutes', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, default='', max_length=20)),
                ('phone_source', models.CharField(blank=True, default='', help_text='Where the number came from (learner/father/teacher_profile/…).', max_length=40)),
                ('verb', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('template_key', models.CharField(blank=True, default='', max_length=50)),
                ('body', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('kind', 'object_id', 'offset_minutes'), name='reminder_once_per_object_offset'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_dd88e2_idx'),
        ),
    ]
