# Generated by Django 6.0.1 on 2026-07-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20260705_1839'),
        ('notifications', '0004_multichannel'),
    ]

    operations = [
    ]
