# Generated by Django 6.0.1 on 2026-07-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merge_0004_merge_20260705_1839_0004_multichannel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_24d4ed_idx',
            old_name='idx_notif_recipient_identity',
        ),
    ]
