# Generated by Django 6.0.1 on 2026-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_idx_notif_recipient_identity_notificatio_recipie_24d4ed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी (Hindi)'), ('bn', 'বাংলা (Bengali)'), ('mr', 'मराठी (Marathi)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('lus', 'Mizo (Lushai)')], default='en', max_length=8),
        ),
    ]
