# Generated by Django 6.0.1 on 2026-08-19 03:21
#
# Adds Notification.track and backfills every existing row from its verb.
#
# The prefix->track map is INLINED rather than imported from
# notifications.tracks on purpose: a data migration must keep reproducing
# the same history forever, and importing the live module would silently
# rewrite what this migration did the next time someone re-tracks a verb.
# If you add a verb, edit tracks.py and (only if old rows need it) write a
# NEW backfill migration.

from django.conf import settings
from django.db import migrations, models

_BACKFILL = [
    ("session.", "academy"),
    ("group.", "academy"),
    ("livestream.", "academy"),
    ("assignment.", "academy"),
    ("quiz.", "academy"),
    ("materials.", "academy"),
    ("enrollment.", "academy"),
    ("skill.", "skill"),
]

# Exact-verb exceptions applied AFTER the prefix sweep, so a later rule
# always wins over a broader earlier one.
_BACKFILL_EXACT = [
    ("payments.receipt", "academy"),
]


def backfill_track(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    for prefix, track in _BACKFILL:
        Notification.objects.filter(
            verb__startswith=prefix
        ).exclude(track=track).update(track=track)
    for verb, track in _BACKFILL_EXACT:
        Notification.objects.filter(verb=verb).exclude(track=track).update(track=track)


def unbackfill_track(apps, schema_editor):
    # Reversing only needs to restore the pre-migration state, and every
    # row was "" before AddField ran. RemoveField drops the column anyway;
    # this exists so the migration is not irreversible.
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.exclude(track="").update(track="")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationpreference_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='track',
            field=models.CharField(blank=True, choices=[('academy', 'Academy'), ('skill', 'Skill Dev')], db_index=True, default='', help_text='Which product track this belongs to: academy / skill. Blank = cross-track (chat, forum, counselling) and shows in BOTH bells. Orthogonal to audience_identity, which separates profiles and CANNOT separate tracks — one TeacherProfile spans both. Derived from the verb by notifications.tracks.track_for_verb() unless the caller passes it explicitly.', max_length=10),
        ),
        migrations.RunPython(backfill_track, unbackfill_track),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'track', 'is_read'], name='notificatio_recipie_7d19c8_idx'),
        ),
    ]
