# Generated by Django 6.0.6 on 2026-06-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(choices=[('free', 'Free (no payment)'), ('manual_upi', 'Manual UPI + admin approval'), ('razorpay', 'Razorpay gateway')], default='free', help_text='How money is collected when something is paid for.', max_length=12)),
                ('free_trial_enabled', models.BooleanField(default=True, help_text='Master switch. While ON, the whole platform behaves as FREE (instant access) regardless of the payment mode above. Turn OFF to start charging using the selected payment mode.')),
                ('upi_id', models.CharField(blank=True, help_text='Platform VPA the student pays to, e.g. shiksha@okaxis', max_length=120)),
                ('upi_payee_name', models.CharField(blank=True, max_length=120)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=200)),
                ('platform_email', models.EmailField(blank=True, help_text='Where subscription / payment notifications are sent.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global settings',
                'verbose_name_plural': 'Global settings',
            },
        ),
    ]
