# Generated by Django 6.0.1 on 2026-07-18 13:55

import global_settings.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='razorpay_key_secret',
            field=global_settings.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
