# Generated by Django 6.0.1 on 2026-08-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_alter_globalsettings_razorpay_key_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='skill_bundle_discount_pct',
            field=models.PositiveSmallIntegerField(default=15, help_text='Discount % off rate×remaining-sessions when buying the full track.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='skill_intro_session_paise',
            field=models.PositiveIntegerField(default=9900, help_text='First-session-ever intro price with a given expert (₹99 default).'),
        ),
    ]
