# Generated by Django 6.0.1 on 2026-08-08 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0003_globalsettings_skill_bundle_discount_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='trial_duration_days',
            field=models.PositiveIntegerField(default=180, help_text='Length of the free-trial window in days (default ~6 months).'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='trial_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the current free-trial countdown began. Reset this (e.g. to restart a 6-month trial from today) via the admin UI.'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='free_trial_enabled',
            field=models.BooleanField(default=True, help_text='Master switch. While ON, the whole platform behaves as FREE (instant access) regardless of the payment mode above. Turn OFF to start charging using the selected payment mode. Also turns itself off automatically once the trial window below elapses — see trial_active / effective_mode.'),
        ),
    ]
