# Generated by Django 6.0.1 on 2026-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0004_globalsettings_trial_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='live_chat_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for in-room chat.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_daily_minutes_per_user',
            field=models.PositiveIntegerField(default=120, help_text='Daily budget per user. 0 disables the daily limit.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_file_retention_days',
            field=models.PositiveIntegerField(default=2, help_text='Days shared files survive after the session ends.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_free_minutes_per_join',
            field=models.PositiveIntegerField(default=15, help_text='Minutes a non-enrolled participant gets per join. Hosts are never capped.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_host_extension_minutes',
            field=models.PositiveIntegerField(default=15, help_text="Minutes added to the room's cap per host extension."),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_host_extensions_allowed',
            field=models.PositiveIntegerField(default=2, help_text='How many times a host may extend one session.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_host_policy',
            field=models.CharField(choices=[('anyone', 'Any signed-in user'), ('teachers_and_enrolled', 'Teachers and enrolled learners'), ('teachers_only', 'Teachers only')], default='teachers_and_enrolled', help_text='Who may host (create/start) a live room.', max_length=24),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_launch_free_mode',
            field=models.BooleanField(default=True, help_text='Launch promo: nobody is time-capped, whatever the values above say.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_max_files_per_session',
            field=models.PositiveIntegerField(default=10, help_text='Max files shared inside one live session.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_max_participants',
            field=models.PositiveIntegerField(default=40, help_text='Hard cap on participants per room, enforced at token issue.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_max_session_minutes',
            field=models.PositiveIntegerField(default=90, help_text="Ceiling for the room's own duration, including host extensions."),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_max_upload_mb',
            field=models.PositiveIntegerField(default=25, help_text='Max size of a single file shared inside a live session.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_recording_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for session recording.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_remote_access_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for teacher screen-control of a student.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_screenshare_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for screen sharing.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='live_show_first_visit_tour',
            field=models.BooleanField(default=True, help_text='Show the first-visit product tour in the live room.'),
        ),
    ]
