# Generated by Django 6.0.1 on 2026-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0005_globalsettings_live_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='tours_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for all product tours across every app.'),
        ),
    ]
