# Generated by Django 6.0.1 on 2026-08-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0006_globalsettings_tours_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ai_question_drafting_enabled',
            field=models.BooleanField(default=False, help_text="Gate for the 'Generate with AI' question-drafting flow."),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='quiz_v2_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the redesigned quiz system UI/flows.'),
        ),
    ]
