# Generated by Django 6.0.1 on 2026-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0008_quiz_v2_enabled_on_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='content_studio_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the restructured Content Studio CMS. While OFF, the existing eight-tab Content panel is shown instead.'),
        ),
    ]
