# Generated by Django 6.0.1 on 2026-08-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0009_globalsettings_content_studio_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='content_studio_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for the restructured Content Studio CMS. While OFF, the remaining Content panel tabs are shown instead.'),
        ),
    ]
