# Generated by Django 6.0.1 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_settings", "0010_alter_globalsettings_content_studio_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="auto_record_classes",
            field=models.BooleanField(
                default=False,
                help_text="Automatically record academy live classes to the recordings library. Billed per minute of class time. Individual courses can override this.",
            ),
        ),
    ]
