# Generated by Django 6.0.1 on 2026-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0010_alter_globalsettings_content_studio_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='google_oauth_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for Google sign-in. While OFF the OAuth endpoint refuses every request, regardless of what the frontend renders.'),
        ),
    ]
