# Generated by Django 6.0.1 on 2026-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0010_alter_globalsettings_content_studio_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='public_quiz_hub_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the public Quiz Hub at /quiz and the admin question-bank authoring screens behind it. While OFF, the placeholder page is shown instead.'),
        ),
    ]
