# Generated by Django 6.0.1 on 2026-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0011 during the integration onto main. main had
        # ALREADY shipped a different 0011 (public_quiz_hub_enabled) plus a
        # 0012, both depending on 0010 — two leaf nodes, which Django
        # refuses to migrate at all. Safe to renumber rather than add a
        # merge migration because this one was never pushed and has never
        # been applied outside a local dev database.
        ('global_settings', '0012_public_quiz_hub_on_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='google_oauth_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for Google sign-in. While OFF the OAuth endpoint refuses every request, regardless of what the frontend renders.'),
        ),
    ]
