# Generated by Django 6.0.1 on 2026-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0013_globalsettings_google_oauth_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='live_ticker_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the CMS live ticker across all its slots — the navbar strip, homepage hero and band, courses rail, footer, student dashboard rail and the login/signup screens. While OFF, none of them render and the existing announcement strip is unaffected.'),
        ),
    ]
